// Bible Diagnostic Quiz — 1 Samuel question bank
// 100 free-response questions covering the narrative arc of 1 Samuel,
// grouped into 7 story sections (used as `category` for sampling and
// the results breakdown, same as the main question bank).
// Self-graded — the app reveals the accepted answer (and any accepted
// alternate phrasings) and the user marks their own typed answer
// correct or incorrect.
//
// Shape: { id, category, prompt, answer, accepted?: [alternate acceptable phrasings] }

const QUESTIONS_1SAMUEL = [

  // ---------------- Samuel's Birth & Calling (ch 1-3) ----------------
  { id: 1001, category: "Samuel's Birth & Calling", prompt: "Who was Samuel's mother, a woman who had been unable to have children?", answer: "Hannah (1 Samuel 1)" },
  { id: 1002, category: "Samuel's Birth & Calling", prompt: "At what sanctuary/shrine did Hannah pray for a son?", answer: "Shiloh (1 Samuel 1)" },
  { id: 1003, category: "Samuel's Birth & Calling", prompt: "What vow did Hannah make about the son she was asking God for?", answer: "She would give him to the LORD for all his life, as a Nazirite (no razor would touch his head) (1 Samuel 1:11)", accepted: ["Dedicate him to the LORD's service"] },
  { id: 1004, category: "Samuel's Birth & Calling", prompt: "Who was the priest at Shiloh who first mistook Hannah's silent prayer for drunkenness?", answer: "Eli (1 Samuel 1:12-14)" },
  { id: 1005, category: "Samuel's Birth & Calling", prompt: "What does the name \"Samuel\" reflect, according to Hannah?", answer: "\"Because I asked the LORD for him\" (1 Samuel 1:20)", accepted: ["It means 'asked of God'"] },
  { id: 1006, category: "Samuel's Birth & Calling", prompt: "After Samuel was weaned, what did Hannah do with him?", answer: "Brought him to Shiloh and gave him to Eli to live and serve at the tabernacle (1 Samuel 1:24-28)" },
  { id: 1007, category: "Samuel's Birth & Calling", prompt: "What themes does Hannah's prayer of praise in 1 Samuel 2 celebrate about God?", answer: "God's holiness and sovereignty — that He humbles the proud and exalts the lowly, brings death and gives life, makes poor and makes rich; often seen as a forerunner to Mary's Magnificat in Luke 1 (1 Samuel 2:1-10)", accepted: ["God's sovereignty over life, death, and social reversal"] },
  { id: 1008, category: "Samuel's Birth & Calling", prompt: "What were the names of Eli's two sons, who served as corrupt priests?", answer: "Hophni and Phinehas (1 Samuel 1:3)" },
  { id: 1009, category: "Samuel's Birth & Calling", prompt: "What kind of misconduct is Eli's sons accused of as priests?", answer: "Taking the best/choicest parts of the people's sacrifices for themselves, and sleeping with women who served at the tabernacle entrance (1 Samuel 2:12-17, 22)", accepted: ["Abusing their priestly office for personal gain"] },
  { id: 1010, category: "Samuel's Birth & Calling", prompt: "How many times did the LORD call to young Samuel in the night before he understood it was God speaking to him?", answer: "Four times (1 Samuel 3:1-10)", accepted: ["4"] },
  { id: 1011, category: "Samuel's Birth & Calling", prompt: "What was the content of God's message to Samuel that first night?", answer: "Judgment on the house of Eli, for his sons' sin and Eli's failure to restrain them (1 Samuel 3:11-14)", accepted: ["Eli's family would be punished"] },
  { id: 1012, category: "Samuel's Birth & Calling", prompt: "By the end of chapter 3, how is Samuel's growing reputation across Israel described?", answer: "The LORD was with him and let none of his words fall to the ground; all Israel from Dan to Beersheba knew he was established as a prophet of the LORD (1 Samuel 3:19-20)", accepted: ["Recognized as a true prophet throughout Israel"] },

  // ---------------- The Ark and the Philistines (ch 4-7) ----------------
  { id: 1013, category: "The Ark and the Philistines", prompt: "Why did the Israelite elders bring the ark of the covenant onto the battlefield against the Philistines?", answer: "Hoping its presence would save them from defeat, after they had already lost the first battle (1 Samuel 4:3)", accepted: ["To help them win/be delivered from the Philistines"] },
  { id: 1014, category: "The Ark and the Philistines", prompt: "What happened to the ark of the covenant in the battle that followed?", answer: "It was captured by the Philistines, and Israel was defeated (1 Samuel 4:10-11)", accepted: ["The Philistines took it"] },
  { id: 1015, category: "The Ark and the Philistines", prompt: "What happened to Eli when he heard the ark had been captured?", answer: "He fell backward off his seat, broke his neck, and died (1 Samuel 4:18)" },
  { id: 1016, category: "The Ark and the Philistines", prompt: "What name was given to Eli's grandson, born the day the ark was captured, and what does it mean?", answer: "Ichabod; it means \"the glory has departed\" (1 Samuel 4:21-22)" },
  { id: 1017, category: "The Ark and the Philistines", prompt: "In what pagan temple did the Philistines place the captured ark, and what happened to the idol there?", answer: "The temple of Dagon in Ashdod; the idol fell facedown before the ark, and on a second night fell again and broke apart (head and hands cut off) (1 Samuel 5:1-4)", accepted: ["Dagon's statue was found broken"] },
  { id: 1018, category: "The Ark and the Philistines", prompt: "What affliction struck the Philistine cities after they took the ark?", answer: "An outbreak of tumors, and the land was infested with mice/rats (1 Samuel 5:6; 6:4-5)", accepted: ["Tumors/plague"] },
  { id: 1019, category: "The Ark and the Philistines", prompt: "How did the Philistines send the ark back to Israel?", answer: "On a new cart pulled by two milk cows, with golden guilt offerings of tumors and mice, letting the cows go without a driver (1 Samuel 6:7-12)", accepted: ["On a cart with no driver, pulled by two cows"] },
  { id: 1020, category: "The Ark and the Philistines", prompt: "What happened to some of the men of Beth-shemesh regarding the returned ark?", answer: "They looked inside the ark and were struck dead by the LORD (1 Samuel 6:19)" },
  { id: 1021, category: "The Ark and the Philistines", prompt: "Where did the ark come to rest for many years after leaving Beth-shemesh?", answer: "Kiriath-jearim (1 Samuel 7:1-2)" },
  { id: 1022, category: "The Ark and the Philistines", prompt: "What did Samuel call on Israel to do before the decisive battle at Mizpah?", answer: "Put away their foreign gods (the Baals and Ashtaroth) and serve the LORD only (1 Samuel 7:3-4)", accepted: ["Get rid of idols and turn back to God"] },
  { id: 1023, category: "The Ark and the Philistines", prompt: "What happened when the Philistines attacked while Samuel was offering a sacrifice at Mizpah?", answer: "The LORD thundered against the Philistines, throwing them into confusion, and Israel routed them (1 Samuel 7:10)", accepted: ["God caused thunder/panic and Israel won"] },
  { id: 1024, category: "The Ark and the Philistines", prompt: "What memorial stone did Samuel set up after this victory, and what did its name mean?", answer: "Ebenezer; \"Thus far the LORD has helped us\" (1 Samuel 7:12)" },
  { id: 1025, category: "The Ark and the Philistines", prompt: "What role did Samuel hold over Israel for the rest of his active life?", answer: "Judge — he went in a yearly circuit to Bethel, Gilgal, and Mizpah, and returned home to Ramah (1 Samuel 7:15-17)", accepted: ["Judge/circuit judge of Israel"] },

  // ---------------- Saul Becomes King (ch 8-12) ----------------
  { id: 1026, category: "Saul Becomes King", prompt: "Why did the elders of Israel ask Samuel to give them a king?", answer: "Samuel was old, his sons (as judges) were corrupt, and the people wanted to be like other nations (1 Samuel 8:1-5)", accepted: ["To be like the other nations"] },
  { id: 1027, category: "Saul Becomes King", prompt: "In what way did Samuel's sons act corruptly as judges?", answer: "They turned aside after dishonest gain, took bribes, and perverted justice (1 Samuel 8:3)", accepted: ["They were greedy and corrupted justice"] },
  { id: 1028, category: "Saul Becomes King", prompt: "How did the LORD tell Samuel to understand Israel's request for a king?", answer: "That the people had not rejected Samuel, but had rejected God as their king (1 Samuel 8:7)", accepted: ["They rejected the LORD, not Samuel"] },
  { id: 1029, category: "Saul Becomes King", prompt: "What are some of the warnings Samuel gave Israel about what a king would do to them?", answer: "Take their sons for his army and chariots, take their daughters as cooks and bakers, take the best of their fields/vineyards/flocks, tax a tenth of their grain and flocks, and make them his servants (1 Samuel 8:11-17)", accepted: ["Any two or three of: conscript sons, take daughters, take land/crops, tax a tenth, take servants"] },
  { id: 1030, category: "Saul Becomes King", prompt: "What was Saul doing when he first crossed paths with Samuel?", answer: "Searching for his father Kish's lost donkeys (1 Samuel 9:3)" },
  { id: 1031, category: "Saul Becomes King", prompt: "From what tribe was Saul, and how is his appearance described?", answer: "The tribe of Benjamin; tall and handsome, a head taller than anyone else (1 Samuel 9:1-2)", accepted: ["Benjamin; very tall and good-looking"] },
  { id: 1032, category: "Saul Becomes King", prompt: "How did Samuel privately anoint Saul as king?", answer: "He poured oil on Saul's head and kissed him (1 Samuel 10:1)" },
  { id: 1033, category: "Saul Becomes King", prompt: "What happened to Saul on his way home after being privately anointed, fulfilling a sign Samuel had predicted?", answer: "The Spirit of God rushed upon him and he prophesied along with a group of prophets (1 Samuel 10:10)", accepted: ["He began to prophesy"] },
  { id: 1034, category: "Saul Becomes King", prompt: "How was Saul publicly chosen as king before all Israel at Mizpah?", answer: "By casting lots, narrowing from tribe (Benjamin) to clan to Saul; he was found hiding among the baggage (1 Samuel 10:20-22)", accepted: ["Chosen by lot; found hiding among the baggage"] },
  { id: 1035, category: "Saul Becomes King", prompt: "What Ammonite king threatened the city of Jabesh-gilead, and what was his cruel condition for peace?", answer: "Nahash; he would only make peace if he could gouge out everyone's right eye (1 Samuel 11:1-2)" },
  { id: 1036, category: "Saul Becomes King", prompt: "How did Saul rally Israel's tribes to rescue Jabesh-gilead?", answer: "He cut a pair of oxen into pieces and sent them throughout Israel as a summons to follow him and Samuel into battle (1 Samuel 11:7)", accepted: ["Sent pieces of cut-up oxen throughout Israel as a call to arms"] },
  { id: 1037, category: "Saul Becomes King", prompt: "How did Saul respond when some in the army wanted to execute the men who had earlier opposed his kingship?", answer: "He refused, saying not a man would be put to death that day, since the LORD had worked salvation in Israel (1 Samuel 11:12-13)", accepted: ["He showed mercy and refused to let them be killed"] },
  { id: 1038, category: "Saul Becomes King", prompt: "What did Israel do at Gilgal to renew Saul's kingship after the victory over the Ammonites?", answer: "They made Saul king before the LORD, offered fellowship offerings/sacrifices, and Saul and all Israel rejoiced greatly (1 Samuel 11:14-15)", accepted: ["Renewed/confirmed his kingship with sacrifices and celebration"] },
  { id: 1039, category: "Saul Becomes King", prompt: "In Samuel's farewell speech, what dramatic sign did he call down from the LORD to show Israel their sin in asking for a king?", answer: "Thunder and rain during the wheat harvest (1 Samuel 12:16-18)" },
  { id: 1040, category: "Saul Becomes King", prompt: "What reassurance did Samuel give Israel even after rebuking them for asking for a king?", answer: "If they and their king would fear and serve the LORD, it would go well for them; he also promised to keep praying for them (1 Samuel 12:14, 23)", accepted: ["Things would be fine if they stayed faithful to God"] },

  // ---------------- Saul's Decline & Rejection (ch 13-15) ----------------
  { id: 1041, category: "Saul's Decline & Rejection", prompt: "In what chapter did Saul commit his first unlawful act, and what did he do?", answer: "1 Samuel 13 — growing impatient waiting for Samuel, he offered the burnt offering himself, a priestly act he wasn't authorized to do", accepted: ["Chapter 13; offered a sacrifice without waiting for Samuel"] },
  { id: 1042, category: "Saul's Decline & Rejection", prompt: "What consequence did Samuel pronounce on Saul for this unlawful sacrifice?", answer: "That his kingdom would not continue/endure; the LORD had already sought out a man after his own heart to be prince instead (1 Samuel 13:13-14)", accepted: ["His dynasty would not last"] },
  { id: 1043, category: "Saul's Decline & Rejection", prompt: "What was notable about weapons and blacksmiths in Israel when they faced the Philistines at Michmash?", answer: "There was no blacksmith in all Israel, so only Saul and Jonathan had swords/spears (1 Samuel 13:19-22)", accepted: ["The Philistines had prevented Israelite blacksmiths"] },
  { id: 1044, category: "Saul's Decline & Rejection", prompt: "In what chapter does Jonathan attack the Philistine garrison at Michmash with only his armor-bearer, trusting that the LORD saves \"by many or by few\"?", answer: "1 Samuel 14 (14:6)" },
  { id: 1045, category: "Saul's Decline & Rejection", prompt: "What happened in the Philistine camp after Jonathan's surprise attack?", answer: "Panic broke out, there was a great trembling/earthquake, and the Philistines fought each other in confusion as Israel routed them (1 Samuel 14:15, 20)", accepted: ["Chaos and panic spread through their camp"] },
  { id: 1046, category: "Saul's Decline & Rejection", prompt: "In what chapter was Saul's rash oath, and what were its conditions?", answer: "1 Samuel 14 — no one could eat anything until evening, until Saul had been avenged on his enemies (14:24)", accepted: ["Chapter 14; a fasting oath until victory"] },
  { id: 1047, category: "Saul's Decline & Rejection", prompt: "How was Jonathan saved from Saul's oath-driven death sentence, after he unknowingly broke it?", answer: "The people intervened and ransomed him, refusing to let him be put to death (1 Samuel 14:45)", accepted: ["The army refused to let Saul kill him"] },
  { id: 1048, category: "Saul's Decline & Rejection", prompt: "What command did the LORD give Saul regarding the Amalekites?", answer: "To completely destroy them — people and livestock, sparing nothing (1 Samuel 15:2-3)", accepted: ["Total destruction (herem) of the Amalekites"] },
  { id: 1049, category: "Saul's Decline & Rejection", prompt: "How did Saul disobey this command against the Amalekites?", answer: "He spared King Agag and kept the best of the sheep and oxen instead of destroying everything (1 Samuel 15:9)", accepted: ["He kept the king alive and the best livestock"] },
  { id: 1050, category: "Saul's Decline & Rejection", prompt: "What is 1 Samuel 15:22-23?", answer: "\"To obey is better than sacrifice, and to listen than the fat of rams... rebellion is as the sin of divination, and presumption is as iniquity and idolatry.\" Because Saul rejected the word of the LORD, the LORD rejected him from being king", accepted: ["To obey is better than sacrifice; rebellion is like divination"] },
  { id: 1051, category: "Saul's Decline & Rejection", prompt: "What did Samuel tell Saul was the final consequence of his disobedience over the Amalekites?", answer: "That the LORD had rejected him as king and torn the kingdom from him, giving it to a neighbor better than him (1 Samuel 15:26-28)", accepted: ["God rejected him as king"] },
  { id: 1052, category: "Saul's Decline & Rejection", prompt: "How does King Agag die?", answer: "Samuel hacks/cuts him to pieces before the LORD at Gilgal (1 Samuel 15:33)" },
  { id: 1053, category: "Saul's Decline & Rejection", prompt: "What was Samuel's response to Saul's rejection, and when does Saul see Samuel next?", answer: "Samuel mourned/grieved for Saul and never went to see him again in life (1 Samuel 15:35); the next time Saul encounters him is as a spirit, summoned by the medium at En-dor after Samuel had already died (1 Samuel 28)", accepted: ["Samuel grieved and avoided him; they only 'meet' again through the medium at En-dor, after Samuel's death"] },

  // ---------------- David's Rise (ch 16-17) ----------------
  { id: 1054, category: "David's Rise", prompt: "Who did the LORD send Samuel to, in order to anoint the next king, and from what town?", answer: "Jesse, of Bethlehem — to anoint one of his sons (1 Samuel 16:1)" },
  { id: 1055, category: "David's Rise", prompt: "What is the verse reference for God's statement to Samuel, \"Man looks on the outward appearance, but the LORD looks on the heart\"?", answer: "1 Samuel 16:7" },
  { id: 1056, category: "David's Rise", prompt: "What was David doing when Samuel came to anoint him?", answer: "Tending/keeping his father's sheep in the field, being the youngest son (1 Samuel 16:11)", accepted: ["Shepherding"] },
  { id: 1057, category: "David's Rise", prompt: "What happened to the Spirit of the LORD regarding Saul and David after David was anointed?", answer: "The Spirit of the LORD rushed upon David from that day forward, and departed from Saul, replaced by a harmful/tormenting spirit (1 Samuel 16:13-14)", accepted: ["The Spirit came on David and left Saul"] },
  { id: 1058, category: "David's Rise", prompt: "Why was David first brought into Saul's service?", answer: "To play the lyre/harp to soothe Saul when the tormenting spirit troubled him; he also became Saul's armor-bearer (1 Samuel 16:21-23)", accepted: ["To play music for Saul"] },
  { id: 1059, category: "David's Rise", prompt: "How many days did Goliath defy/taunt Israel before David arrived?", answer: "40 days (1 Samuel 17:16)", accepted: ["Forty"] },
  { id: 1060, category: "David's Rise", prompt: "Why did David happen to be at the battle lines where Goliath was taunting Israel?", answer: "His father sent him to bring supplies to his brothers in the army and check on them (1 Samuel 17:17-19)", accepted: ["Bringing food to his brothers"] },
  { id: 1061, category: "David's Rise", prompt: "What reward did Saul offer to whoever killed Goliath?", answer: "Great riches, his daughter in marriage, and freedom from taxes for his father's house (1 Samuel 17:25)", accepted: ["Wealth, marriage to Saul's daughter, and tax exemption"] },
  { id: 1062, category: "David's Rise", prompt: "Why did David refuse to wear Saul's armor into battle with Goliath?", answer: "He wasn't used to it/hadn't tested it (1 Samuel 17:39)", accepted: ["He hadn't tried it before and it didn't fit his fighting style"] },
  { id: 1063, category: "David's Rise", prompt: "How many stones did David pick up before facing Goliath?", answer: "Five smooth stones (1 Samuel 17:40)", accepted: ["Five", "5"] },
  { id: 1064, category: "David's Rise", prompt: "What did David do with Goliath's head and armor after the battle?", answer: "He brought Goliath's head to Jerusalem, and put his armor in his own tent (1 Samuel 17:54)" },
  { id: 1065, category: "David's Rise", prompt: "What happened to the Philistine army after Goliath fell?", answer: "They fled, and Israel pursued and struck them down (1 Samuel 17:51-52)", accepted: ["They ran away and were routed"] },

  // ---------------- David and Saul's Conflict (ch 18-27) ----------------
  { id: 1066, category: "David and Saul's Conflict", prompt: "What happens right at the beginning of 1 Samuel 18?", answer: "Jonathan's soul was knit to David's soul; he loved David as his own soul and made a covenant with him, giving David his robe, armor, sword, bow, and belt (18:1-4)", accepted: ["Jonathan and David form a covenant of friendship"] },
  { id: 1067, category: "David and Saul's Conflict", prompt: "How did Saul become jealous of David?", answer: "After a battle, the women sang, \"Saul has struck down his thousands, and David his ten thousands,\" which angered Saul (1 Samuel 18:6-9)" },
  { id: 1068, category: "David and Saul's Conflict", prompt: "What did Saul attempt to do to David twice in this episode, while David played the lyre for him?", answer: "Hurled his spear at David, trying to pin him to the wall — David evaded him twice within this episode in 1 Samuel 18:10-11 (a separate, similar attempt happens again later, in 19:9-10)", accepted: ["Tried to spear him"] },
  { id: 1069, category: "David and Saul's Conflict", prompt: "What bride price did Saul demand for his daughter Michal?", answer: "100 Philistine foreskins (David brought 200) (1 Samuel 18:25-27)", accepted: ["100 foreskins of the Philistines"] },
  { id: 1070, category: "David and Saul's Conflict", prompt: "After David fled, who did Saul give Michal to in marriage instead?", answer: "Palti (Paltiel) son of Laish (1 Samuel 25:44)" },
  { id: 1071, category: "David and Saul's Conflict", prompt: "How does David first escape from Saul's assassins?", answer: "Michal lets him down through a window at night, then puts a household idol in the bed to fool the pursuers and buy him time (1 Samuel 19:11-13)", accepted: ["Lowered him out a window and used a decoy in the bed"] },
  { id: 1072, category: "David and Saul's Conflict", prompt: "In 1 Samuel 19, where does David flee to, and what happens to Saul's messengers (and Saul himself) when they try to capture him there?", answer: "To Samuel at Naioth in Ramah; the messengers, and then Saul, begin prophesying instead of capturing him (19:18-24)", accepted: ["They started prophesying when they arrived"] },
  { id: 1073, category: "David and Saul's Conflict", prompt: "How was Jonathan going to indicate to David whether it was safe to return?", answer: "By shooting arrows near a rock and telling a boy where to find them — arrows shot \"beyond\" the boy meant danger, run away (1 Samuel 20:18-22)", accepted: ["An arrow-shooting signal to a boy retrieving them"] },
  { id: 1074, category: "David and Saul's Conflict", prompt: "In 1 Samuel 21, what did the priest Ahimelech at Nob give David to eat, and what weapon did he also give him?", answer: "The consecrated bread (the showbread), and Goliath's sword, which had been kept behind the ephod (21:1-9)", accepted: ["Holy bread and Goliath's sword"] },
  { id: 1075, category: "David and Saul's Conflict", prompt: "Who witnessed David at Nob and later reported it to Saul, leading to tragedy?", answer: "Doeg the Edomite (1 Samuel 21:7; 22:9-10)" },
  { id: 1076, category: "David and Saul's Conflict", prompt: "What happens to the priests of Nob and the town itself in 1 Samuel 22?", answer: "Saul has Doeg kill 85 priests, and destroys the town of Nob entirely — men, women, children, and animals (22:18-19)", accepted: ["Massacred the priests and the whole town"] },
  { id: 1077, category: "David and Saul's Conflict", prompt: "Which priest survived the massacre at Nob and joined David?", answer: "Abiathar (1 Samuel 22:20-23)" },
  { id: 1078, category: "David and Saul's Conflict", prompt: "How did David escape capture while in Philistine territory at Gath?", answer: "He pretended to be insane/feigned madness before King Achish (1 Samuel 21:12-15)", accepted: ["Acted crazy to avoid being taken seriously as a threat"] },
  { id: 1079, category: "David and Saul's Conflict", prompt: "Where did David hide after fleeing Gath, and who gathered to him there?", answer: "The cave of Adullam; those in distress, in debt, or discontented gathered to him, about 400 men (1 Samuel 22:1-2)", accepted: ["Cave of Adullam; outcasts and debtors joined him"] },
  { id: 1080, category: "David and Saul's Conflict", prompt: "Which city did David rescue from a Philistine raid, after first inquiring of the LORD?", answer: "Keilah (1 Samuel 23:1-5)" },
  { id: 1081, category: "David and Saul's Conflict", prompt: "What did Jonathan say to David when he visited him in the wilderness of Ziph, and what did he acknowledge?", answer: "He strengthened David's hand in God, told him not to be afraid because Saul would not find him, and acknowledged that David would be king over Israel, with Jonathan next to him (1 Samuel 23:16-18)", accepted: ["Encouraged David and acknowledged he would be king"] },
  { id: 1082, category: "David and Saul's Conflict", prompt: "Who repeatedly betrayed David's location to Saul?", answer: "The Ziphites (1 Samuel 23:19-20)" },
  { id: 1083, category: "David and Saul's Conflict", prompt: "What is the \"Rock of Escape\"?", answer: "The place (Sela-hammahlekoth) where Saul was pursuing David around a mountain until news of a Philistine raid pulled Saul away, forcing him to break off the chase (1 Samuel 23:26-28)", accepted: ["Where Saul nearly caught David but was called away by a Philistine raid"] },
  { id: 1084, category: "David and Saul's Conflict", prompt: "Where did David first spare Saul's life, cutting off a corner of his robe instead of killing him?", answer: "A cave at En-gedi (1 Samuel 24:1-4)" },
  { id: 1085, category: "David and Saul's Conflict", prompt: "What kind of protection had David's men provided Nabal's shepherds before Nabal refused to repay them?", answer: "They had guarded Nabal's shepherds and flocks in the wilderness, so nothing was missing the whole time (1 Samuel 25:15-16, 21)", accepted: ["They protected his flocks without taking anything"] },
  { id: 1086, category: "David and Saul's Conflict", prompt: "What does Abigail say about the meaning of Nabal's name when she pleads with David?", answer: "\"Nabal\" means \"fool,\" and folly is with him (1 Samuel 25:25)" },
  { id: 1087, category: "David and Saul's Conflict", prompt: "After Nabal's death, how does David come to marry Abigail?", answer: "David sends messengers proposing marriage; Abigail quickly goes with her attendants and becomes his wife (1 Samuel 25:39-42)" },
  { id: 1088, category: "David and Saul's Conflict", prompt: "Where did David spare Saul's life a second time, taking his spear and water jug instead of killing him?", answer: "Saul's camp at Hakilah, sneaking in at night with Abishai (1 Samuel 26:6-12)", accepted: ["Hakilah"] },

  // ---------------- Saul's End & David in Exile (ch 28-31) ----------------
  { id: 1089, category: "Saul's End & David in Exile", prompt: "Where did David go to live under Philistine protection to escape Saul for good, and which king gave him a town to live in?", answer: "Gath, under King Achish; given the town of Ziklag (1 Samuel 27:2-6)" },
  { id: 1090, category: "Saul's End & David in Exile", prompt: "Whom did David actually raid while living in Ziklag, while deceiving Achish about his targets?", answer: "Peoples like the Geshurites, Girzites, and Amalekites, while telling Achish he was raiding Judah/Israel instead (1 Samuel 27:8-10)", accepted: ["Nearby raiding parties, while lying to Achish about who he attacked"] },
  { id: 1091, category: "Saul's End & David in Exile", prompt: "Why did Saul consult a medium at En-dor before his final battle?", answer: "The LORD would not answer him, whether by dreams, Urim, or prophets, and he was desperate for guidance (1 Samuel 28:6)", accepted: ["God had stopped answering him"] },
  { id: 1092, category: "Saul's End & David in Exile", prompt: "What had Saul himself done regarding mediums and necromancers, before he ironically went to consult one at En-dor?", answer: "He had expelled/banned mediums and necromancers from the land (1 Samuel 28:3, 9)", accepted: ["He had outlawed mediums earlier in his reign"] },
  { id: 1093, category: "Saul's End & David in Exile", prompt: "What did Samuel's spirit predict would happen to Saul and his sons?", answer: "That Saul and his sons would die the following day, and Israel would be defeated by the Philistines (1 Samuel 28:19)", accepted: ["Saul and his sons would die, Israel would lose the battle"] },
  { id: 1094, category: "Saul's End & David in Exile", prompt: "Why did the Philistine commanders send David back to Ziklag instead of letting him fight alongside them against Israel?", answer: "They didn't trust him and feared he'd turn on them during the battle (1 Samuel 29:3-4)", accepted: ["They were suspicious he might betray them"] },
  { id: 1095, category: "Saul's End & David in Exile", prompt: "What happens in 1 Samuel 30?", answer: "David returns to Ziklag to find it raided and burned by the Amalekites, with the wives and families taken captive; after inquiring of the LORD, he pursues, recovers everyone and everything, and establishes a rule for splitting the plunder", accepted: ["Ziklag is raided and David recovers everyone and everything"] },
  { id: 1096, category: "Saul's End & David in Exile", prompt: "How did David and his men find/track the Amalekite raiders?", answer: "With help from an abandoned Egyptian servant, left behind by the Amalekites, who guided them to the raiding camp (1 Samuel 30:11-15)", accepted: ["A rescued Egyptian slave led them there"] },
  { id: 1097, category: "Saul's End & David in Exile", prompt: "What rule did David establish about dividing the plunder recovered from the Amalekites?", answer: "Those who stayed behind with the supplies would share the plunder equally with those who went into battle (1 Samuel 30:24-25)", accepted: ["Equal shares for those who fought and those who guarded the camp"] },
  { id: 1098, category: "Saul's End & David in Exile", prompt: "What did the Philistines do with Saul's body and armor after finding him dead on the battlefield?", answer: "They cut off his head, stripped his armor, sent word throughout Philistine land and displayed it in the temples of their idols, and fastened his body to the wall of Beth-shan (1 Samuel 31:9-10)", accepted: ["Desecrated his body and displayed it publicly"] },
  { id: 1099, category: "Saul's End & David in Exile", prompt: "Which notable figures die in the final battle between Israel and the Philistines?", answer: "Saul and three of his sons — Jonathan, Abinadab, and Malchi-shua (1 Samuel 31:2, 6)", accepted: ["Saul and his sons, including Jonathan"] },
  { id: 1100, category: "Saul's End & David in Exile", prompt: "How did Saul die, and what did the men of Jabesh-gilead do afterward out of gratitude for his earlier rescue of their city?", answer: "He fell on his own sword to avoid capture after being critically wounded by archers; the men of Jabesh-gilead retrieved his body (and his sons') by night, burned/buried the bones under a tamarisk tree, and fasted seven days (1 Samuel 31:3-13)", accepted: ["Suicide by his own sword; Jabesh-gilead recovered and buried the bodies"] },

];
