// Bible Diagnostic Quiz — 2 Samuel question bank
// 100 free-response questions covering the narrative arc of 2 Samuel,
// grouped into 7 story sections (used as `category` for sampling and
// the results breakdown, same as the main question bank and the
// 1 Samuel bank).
// Self-graded — the app reveals the accepted answer (and any accepted
// alternate phrasings) and the user marks their own typed answer
// correct or incorrect. Chapter/verse references are given in the
// answer only, never in the prompt, except where a question is
// specifically about identifying a chapter/reference itself.
//
// Shape: { id, category, prompt, answer, accepted?: [alternate acceptable phrasings] }

const QUESTIONS_2SAMUEL = [

  // ---------------- David's Rise to the Throne (ch 1-5) ----------------
  { id: 2001, category: "David's Rise to the Throne", prompt: "Who brought David the news of Saul's and Jonathan's deaths, and what did he claim about his own role in Saul's death?", answer: "An Amalekite young man from Saul's camp; he claimed Saul, mortally wounded, asked him to finish him off (2 Samuel 1:1-10)", accepted: ["An Amalekite messenger who claimed to have killed Saul at his own request"] },
  { id: 2002, category: "David's Rise to the Throne", prompt: "What did David do to the Amalekite messenger after hearing his claim, and why?", answer: "Had him executed, for daring to kill \"the LORD's anointed\" (2 Samuel 1:14-16)" },
  { id: 2003, category: "David's Rise to the Throne", prompt: "Where had David and his men just returned from when they heard the news of Saul's death?", answer: "Ziklag, after striking down the Amalekites who had earlier raided and burned the town (2 Samuel 1:1)" },
  { id: 2004, category: "David's Rise to the Throne", prompt: "What tokens did the Amalekite young man bring to David as proof of Saul's death?", answer: "Saul's crown and the armband from his arm (2 Samuel 1:10)", accepted: ["His crown and armlet/bracelet"] },
  { id: 2005, category: "David's Rise to the Throne", prompt: "How did David and his men respond immediately upon hearing the news of Saul, Jonathan, and Israel's defeat?", answer: "They tore their clothes, mourned, wept, and fasted until evening (2 Samuel 1:11-12)" },
  { id: 2006, category: "David's Rise to the Throne", prompt: "What question did David ask the young man before ordering his execution?", answer: "\"How did you dare to destroy the LORD's anointed?\" (2 Samuel 1:14)" },
  { id: 2007, category: "David's Rise to the Throne", prompt: "According to the young man's own account, where did he encounter the wounded Saul?", answer: "On Mount Gilboa, where Saul was leaning on his spear as enemy chariots and horsemen closed in (2 Samuel 1:6)" },
  { id: 2008, category: "David's Rise to the Throne", prompt: "How does the text explain the justice of the Amalekite's execution?", answer: "His own blood was on his own head, since he had testified against himself by claiming to have killed the LORD's anointed (2 Samuel 1:16)" },
  { id: 2009, category: "David's Rise to the Throne", prompt: "After Saul's death, where did David go (having inquired of the LORD), and who anointed him king there?", answer: "Hebron; the men of Judah anointed him king over the house of Judah (2 Samuel 2:1-4)" },
  { id: 2010, category: "David's Rise to the Throne", prompt: "Who did Saul's general Abner make king over the rest of Israel, ruling from Mahanaim, in opposition to David?", answer: "Ish-bosheth, Saul's son (2 Samuel 2:8-10)" },
  { id: 2011, category: "David's Rise to the Throne", prompt: "What contest between young men of Joab's and Abner's forces at Gibeon's pool escalated into a full battle?", answer: "A staged combat where twelve young men from each side fought and killed each other simultaneously (2 Samuel 2:14-17)", accepted: ["A mutual duel between twelve men from each side"] },
  { id: 2012, category: "David's Rise to the Throne", prompt: "Who was Asahel, and how did he die?", answer: "Joab's brother; he refused to stop chasing Abner, who reluctantly killed him with the back end of his spear (2 Samuel 2:18-23)" },
  { id: 2013, category: "David's Rise to the Throne", prompt: "What accusation by Ish-bosheth caused Abner to break with Saul's house and defect toward David?", answer: "That Abner had taken Saul's concubine Rizpah (2 Samuel 3:6-11)" },
  { id: 2014, category: "David's Rise to the Throne", prompt: "What condition did David set before he would make a covenant with Abner?", answer: "That his wife Michal, Saul's daughter, be returned to him first (2 Samuel 3:12-16)" },
  { id: 2015, category: "David's Rise to the Throne", prompt: "How did Abner die, and who killed him?", answer: "Joab murdered him at the gate of Hebron, partly in revenge for Asahel, after David had already made peace with him (2 Samuel 3:26-27)" },
  { id: 2016, category: "David's Rise to the Throne", prompt: "How did David publicly respond to Abner's murder?", answer: "He mourned/wept at Abner's tomb, composed a lament for him, fasted, and publicly declared his own innocence in the killing while cursing Joab's house (2 Samuel 3:28-35)", accepted: ["He grieved publicly and denounced the killing"] },
  { id: 2017, category: "David's Rise to the Throne", prompt: "How did Ish-bosheth die?", answer: "Murdered in his bed by two of his own captains, Rechab and Baanah, who beheaded him (2 Samuel 4:5-7)" },
  { id: 2018, category: "David's Rise to the Throne", prompt: "What did David do to Ish-bosheth's killers?", answer: "Had them executed, for killing an innocent man in his own house (2 Samuel 4:9-12)" },
  { id: 2019, category: "David's Rise to the Throne", prompt: "After Ish-bosheth's death, what did all the tribes of Israel do?", answer: "Came to David at Hebron and anointed him king over all Israel (2 Samuel 5:1-3)" },
  { id: 2020, category: "David's Rise to the Throne", prompt: "How long did David reign as king?", answer: "40 years total — 7 years over Judah in Hebron, then 33 years over all Israel in Jerusalem (2 Samuel 5:4-5)", accepted: ["40 years"] },
  { id: 2021, category: "David's Rise to the Throne", prompt: "What city did David capture to make his new capital, and what was it renamed?", answer: "Jerusalem, taken from the Jebusites; renamed the City of David (2 Samuel 5:6-9)" },
  { id: 2022, category: "David's Rise to the Throne", prompt: "Which foreign king sent David materials and craftsmen to build his palace?", answer: "Hiram, king of Tyre (2 Samuel 5:11)" },
  { id: 2023, category: "David's Rise to the Throne", prompt: "When the Philistines attacked a second time after hearing David was king over all Israel, what instruction did the LORD give him?", answer: "To wait until he heard the sound of marching in the tops of the balsam trees before attacking (2 Samuel 5:22-24)" },
  { id: 2024, category: "David's Rise to the Throne", prompt: "What was the outcome when David fought the Philistines in the Valley of Rephaim?", answer: "He defeated them decisively, on both occasions he was attacked there (2 Samuel 5:17-25)" },

  // ---------------- The Ark & the Davidic Covenant (ch 6-7) ----------------
  { id: 2025, category: "The Ark & the Davidic Covenant", prompt: "Who was Uzzah?", answer: "A son of Abinadab, in whose house the ark had rested for years; he was guiding the cart carrying the ark and was struck dead by the LORD when he reached out to steady it (2 Samuel 6:3-7)" },
  { id: 2026, category: "The Ark & the Davidic Covenant", prompt: "What was improper about the ark's transportation?", answer: "It was carried on a new cart pulled by oxen instead of being carried on the shoulders of the Levites as prescribed (2 Samuel 6:3)", accepted: ["Carried on a cart instead of by the Levites"] },
  { id: 2027, category: "The Ark & the Davidic Covenant", prompt: "Where did David leave the ark for three months after Uzzah's death, and what happened there?", answer: "The house of Obed-edom the Gittite; the LORD blessed Obed-edom and his household (2 Samuel 6:10-11)" },
  { id: 2028, category: "The Ark & the Davidic Covenant", prompt: "How did David bring the ark into Jerusalem the second time?", answer: "He danced before the LORD with all his might, wearing a linen ephod, while the ark was carried properly with sacrifices offered every six steps (2 Samuel 6:13-14)" },
  { id: 2029, category: "The Ark & the Davidic Covenant", prompt: "Who despised David in her heart for how he danced before the ark, and what was the lasting consequence for her?", answer: "Michal, Saul's daughter; she remained childless for the rest of her life (2 Samuel 6:16, 20-23)" },
  { id: 2030, category: "The Ark & the Davidic Covenant", prompt: "What contrast does David point out to Nathan about his own house compared to the ark's dwelling, in 2 Samuel 7:2?", answer: "That he lived in a house of cedar while the ark of God dwelt in a tent (2 Samuel 7:2)" },
  { id: 2031, category: "The Ark & the Davidic Covenant", prompt: "What plan did David have in 2 Samuel 7, and what did the prophet Nathan initially tell David about it?", answer: "David wanted to build a house/temple for the ark; Nathan initially told him to go ahead, since the LORD was with him (2 Samuel 7:2-3)" },
  { id: 2032, category: "The Ark & the Davidic Covenant", prompt: "What did the LORD tell Nathan later to relay about David's plan to build a temple?", answer: "That David would not build the house; instead, one of his own offspring would build it, and the LORD would build David a \"house\" — a dynasty — instead (2 Samuel 7:5-13)", accepted: ["David's son would build the temple; God would build David a dynasty"] },
  { id: 2033, category: "The Ark & the Davidic Covenant", prompt: "What is promised about David's throne and dynasty in the covenant of 2 Samuel 7?", answer: "That his house, kingdom, and throne would be established forever (2 Samuel 7:16)" },
  { id: 2034, category: "The Ark & the Davidic Covenant", prompt: "How does the LORD describe His future relationship with David's offspring (Solomon) in the covenant of 2 Samuel 7?", answer: "\"I will be to him a father, and he shall be to me a son\"; if he sins, God will discipline him, but His steadfast love will never be taken away from him (2 Samuel 7:14-15)" },
  { id: 2035, category: "The Ark & the Davidic Covenant", prompt: "How did David respond after hearing Nathan relay the covenant promise of 2 Samuel 7?", answer: "He went in and sat before the LORD, praying with humility and gratitude (2 Samuel 7:18-29)" },
  { id: 2036, category: "The Ark & the Davidic Covenant", prompt: "What does David marvel at about himself and his house in his prayer of response to the covenant of 2 Samuel 7?", answer: "That God would make such a promise to someone as insignificant as him and his house (2 Samuel 7:18)", accepted: ["\"Who am I... that you have brought me this far?\""] },
  { id: 2037, category: "The Ark & the Davidic Covenant", prompt: "What request does David make regarding his family and future generations at the end of his prayer?", answer: "He asks the LORD to bless his house so that it may continue forever before Him (2 Samuel 7:29)" },
  { id: 2038, category: "The Ark & the Davidic Covenant", prompt: "Which prophet both delivers the Davidic covenant to David in chapter 7 and later confronts him over Bathsheba in chapter 12?", answer: "Nathan (2 Samuel 7; 12)" },

  // ---------------- David's Military Victories (ch 8-10) ----------------
  { id: 2039, category: "David's Military Victories", prompt: "Besides the Philistines, name two other peoples/kingdoms David defeated according to the summary in chapter 8.", answer: "Any two of: Moab, Hadadezer of Zobah (the Arameans/Syrians), Edom (2 Samuel 8:1-14)", accepted: ["Any two of: Moab, Zobah/Syria, Edom"] },
  { id: 2040, category: "David's Military Victories", prompt: "How did David deal with the Moabite prisoners after defeating them?", answer: "He measured them with a cord, killing two-thirds and letting one-third live, and Moab became his tribute-paying subjects (2 Samuel 8:2)" },
  { id: 2041, category: "David's Military Victories", prompt: "What did David do with the silver and gold plunder he took from his defeated enemies?", answer: "Dedicated it to the LORD (2 Samuel 8:11-12)" },
  { id: 2042, category: "David's Military Victories", prompt: "Who was Joab in David's administration?", answer: "Commander of the army (2 Samuel 8:16)" },
  { id: 2043, category: "David's Military Victories", prompt: "Why did David seek out anyone remaining from Saul's household in chapter 9?", answer: "To show kindness to them for Jonathan's sake, because of his covenant of friendship with Jonathan (2 Samuel 9:1, 7)" },
  { id: 2044, category: "David's Military Victories", prompt: "Who was Mephibosheth, and what had happened to him as a child?", answer: "Jonathan's son; he was dropped and injured while fleeing as a child after Saul and Jonathan's deaths, leaving him lame in both feet (2 Samuel 4:4; 9:3)" },
  { id: 2045, category: "David's Military Victories", prompt: "What did David restore to Mephibosheth, and what ongoing privilege did he grant him?", answer: "Restored all the land that had belonged to Saul, and had him eat at the king's table always, like one of David's own sons (2 Samuel 9:7-11)" },
  { id: 2046, category: "David's Military Victories", prompt: "Who was appointed to manage Mephibosheth's land on his behalf?", answer: "Ziba, Saul's former servant (2 Samuel 9:9-10)" },
  { id: 2047, category: "David's Military Victories", prompt: "Why did war break out between David and the Ammonites in chapter 10?", answer: "David sent envoys to console the new Ammonite king Hanun after his father's death, but Hanun's princes convinced him David's men were spies (2 Samuel 10:1-4)", accepted: ["Hanun's advisors suspected David's condolence envoys of being spies"] },
  { id: 2048, category: "David's Military Victories", prompt: "What humiliation did Hanun inflict on David's envoys?", answer: "Shaved off half of each man's beard and cut off their garments at the buttocks, then sent them away (2 Samuel 10:4)" },
  { id: 2049, category: "David's Military Victories", prompt: "Knowing they had angered David, what did the Ammonites do to prepare for war?", answer: "Hired Syrian/Aramean mercenaries to fight alongside them (2 Samuel 10:6)" },
  { id: 2050, category: "David's Military Victories", prompt: "How did Joab handle being caught between two enemy fronts (Ammonites and Syrians) in this battle?", answer: "He split his forces, taking the best troops against the Syrians himself and giving the rest to his brother Abishai against the Ammonites, agreeing to help each other if needed (2 Samuel 10:9-11)" },
  { id: 2051, category: "David's Military Victories", prompt: "What was the ultimate outcome after David personally led Israel against the regrouped Syrian forces?", answer: "Israel defeated them decisively; the Syrians made peace with Israel and stopped helping the Ammonites (2 Samuel 10:15-19)" },
  { id: 2052, category: "David's Military Victories", prompt: "How did the war with the Ammonites, begun in chapter 10, finally conclude?", answer: "Joab captured the Ammonite capital Rabbah; David took the crown from the Ammonite king's head, plundered the city, and subjected its people to forced labor (2 Samuel 12:26-31)" },

  // ---------------- David and Bathsheba (ch 11-12) ----------------
  { id: 2053, category: "David and Bathsheba", prompt: "What is unusual about David at the start of chapter 11?", answer: "It was \"the time when kings go out to battle,\" but David stayed behind in Jerusalem instead of leading the army himself, sending Joab in his place (2 Samuel 11:1)" },
  { id: 2054, category: "David and Bathsheba", prompt: "What happens at the very beginning of 2 Samuel 11, involving David's rooftop?", answer: "David sees Bathsheba bathing from his rooftop, sends messengers to inquire about her, and has her brought to him (2 Samuel 11:2-4)" },
  { id: 2055, category: "David and Bathsheba", prompt: "Who was Bathsheba married to at the time?", answer: "Uriah the Hittite (2 Samuel 11:3)" },
  { id: 2056, category: "David and Bathsheba", prompt: "After Bathsheba became pregnant, what was David's first attempt to cover up the affair?", answer: "He recalled Uriah from the battlefield, hoping he would sleep with his wife so the child would appear to be his (2 Samuel 11:6-8)" },
  { id: 2057, category: "David and Bathsheba", prompt: "Why did Uriah refuse to go home to his wife while on leave from battle?", answer: "Out of loyalty to his fellow soldiers and the ark, who were camping out in the field — he felt he couldn't enjoy comforts they didn't have (2 Samuel 11:9-11)", accepted: ["Solidarity with his fellow soldiers still at war"] },
  { id: 2058, category: "David and Bathsheba", prompt: "After Uriah refused to go home even while drunk, what did David ultimately arrange?", answer: "Sent Uriah back to the battle with a sealed letter to Joab, ordering that Uriah be placed in the fiercest fighting and then abandoned so he would be killed (2 Samuel 11:14-15)" },
  { id: 2059, category: "David and Bathsheba", prompt: "What did David do after Bathsheba's period of mourning for Uriah ended?", answer: "Took her as his wife; she bore him a son (2 Samuel 11:26-27)" },
  { id: 2060, category: "David and Bathsheba", prompt: "How does the narrator summarize God's view of what David had done?", answer: "\"The thing that David had done displeased the LORD\" (2 Samuel 11:27)" },
  { id: 2061, category: "David and Bathsheba", prompt: "What parable did Nathan the prophet use to confront David about his sin?", answer: "A rich man with many flocks stole and slaughtered a poor man's one beloved ewe lamb to feed a guest (2 Samuel 12:1-4)" },
  { id: 2062, category: "David and Bathsheba", prompt: "What did David unknowingly declare about himself when he angrily judged the rich man in Nathan's parable?", answer: "That the man deserved to die and should restore the lamb fourfold (2 Samuel 12:5-6)" },
  { id: 2063, category: "David and Bathsheba", prompt: "What did Nathan finally say to David after telling the parable?", answer: "\"You are the man!\" (2 Samuel 12:7)" },
  { id: 2064, category: "David and Bathsheba", prompt: "What judgment did Nathan pronounce on David's household as a consequence of his sin?", answer: "That the sword would never depart from his house, that calamity would rise against him from within his own household, and that his wives would be given to another in broad daylight (2 Samuel 12:10-11)", accepted: ["Ongoing violence within his family, and his wives taken by another"] },
  { id: 2065, category: "David and Bathsheba", prompt: "What did David say when he confessed his sin to Nathan, and what did Nathan say in response?", answer: "David said, \"I have sinned against the LORD\"; Nathan told him the LORD had put away his sin and he would not die, but the child born to him would die (2 Samuel 12:13-14)" },
  { id: 2066, category: "David and Bathsheba", prompt: "What does David do once the first child he and Bathsheba conceived dies?", answer: "He gets up, washes, anoints himself, changes his clothes, worships the LORD, and then eats — explaining to his surprised servants that while the child was alive he fasted and wept hoping God would be gracious, but now that the child was dead there was no reason to fast; he could not bring the child back, but he would go to him (2 Samuel 12:20-23)", accepted: ["He stops mourning, worships, and resumes eating"] },
  { id: 2067, category: "David and Bathsheba", prompt: "After the first child died, what son did Bathsheba later bear David, and what name did Nathan give him, meaning \"beloved of the LORD\"?", answer: "Solomon; Nathan named him Jedidiah, because the LORD loved him (2 Samuel 12:24-25)" },

  // ---------------- Absalom's Rebellion (ch 13-20) ----------------
  { id: 2068, category: "Absalom's Rebellion", prompt: "Who was Amnon, and who did he develop an obsessive desire for?", answer: "David's firstborn son; his half-sister Tamar, Absalom's full sister (2 Samuel 13:1-2)" },
  { id: 2069, category: "Absalom's Rebellion", prompt: "How did Amnon's cousin Jonadab help him get access to Tamar?", answer: "Advised him to feign illness and ask David to send Tamar to prepare food for him personally (2 Samuel 13:3-6)" },
  { id: 2070, category: "Absalom's Rebellion", prompt: "What did Amnon do to Tamar despite her pleas, and how did she visibly show her grief and disgrace afterward?", answer: "He raped her, then hated her more than he had loved her and threw her out; she tore her robe (worn by virgin daughters of the king), put ashes on her head, and lived desolate in Absalom's house (2 Samuel 13:14-20)", accepted: ["He raped and rejected her; she mourned openly as a disgraced woman"] },
  { id: 2071, category: "Absalom's Rebellion", prompt: "How long did Absalom wait before avenging Tamar, and how did he kill Amnon?", answer: "Two years; he had his servants kill Amnon at a sheep-shearing feast while he was drunk (2 Samuel 13:23-29)" },
  { id: 2072, category: "Absalom's Rebellion", prompt: "What did Absalom do immediately after killing Amnon?", answer: "Fled to his grandfather Talmai, king of Geshur, staying there three years (2 Samuel 13:37-38)" },
  { id: 2073, category: "Absalom's Rebellion", prompt: "Who persuaded David to allow Absalom to return to Jerusalem, and how?", answer: "Joab, through a wise woman of Tekoa who told David a staged parable, similar to Nathan's, persuading him to bring his banished son home (2 Samuel 14:1-21)" },
  { id: 2074, category: "Absalom's Rebellion", prompt: "Even after Absalom returned to Jerusalem, how did David treat him for two years?", answer: "Allowed him to live in the city but refused to let him come into his presence/see his face (2 Samuel 14:24, 28)" },
  { id: 2075, category: "Absalom's Rebellion", prompt: "How did Absalom finally force a meeting with Joab (and through him, David)?", answer: "He had his servants set Joab's barley field on fire to get his attention (2 Samuel 14:29-32)" },
  { id: 2076, category: "Absalom's Rebellion", prompt: "How did Absalom win over the hearts of the people of Israel before launching his rebellion at Hebron?", answer: "He rose early, stood by the city gate, and told people coming for the king's judgment that their case was right but there was no one appointed to hear them, wishing he were judge himself; he later left for Hebron under the pretext of fulfilling a vow (2 Samuel 15:1-9)", accepted: ["He flattered people seeking judgment, then used a vow as pretext to gather forces at Hebron"] },
  { id: 2077, category: "Absalom's Rebellion", prompt: "Who was David's trusted counselor who defected to join Absalom's conspiracy?", answer: "Ahithophel (2 Samuel 15:12)" },
  { id: 2078, category: "Absalom's Rebellion", prompt: "What did David do with the ark when he fled Jerusalem, and why?", answer: "He sent it back into the city with the priest Zadok, trusting the LORD to bring him back if He was pleased with him, rather than treating the ark as a good-luck charm (2 Samuel 15:24-29)" },
  { id: 2079, category: "Absalom's Rebellion", prompt: "Who cursed David and threw stones and dust at him as he fled, and how did David respond?", answer: "Shimei, a man from Saul's clan; David refused to let Abishai kill him, accepting it as possibly permitted by the LORD (2 Samuel 16:5-13)" },
  { id: 2080, category: "Absalom's Rebellion", prompt: "What claim did Ziba make about Mephibosheth to David while David was fleeing, and what did David do as a result?", answer: "Claimed Mephibosheth had stayed behind hoping to reclaim Saul's kingdom; David gave Ziba all of Mephibosheth's property (2 Samuel 16:1-4)" },
  { id: 2081, category: "Absalom's Rebellion", prompt: "What was the first advice recorded from Ahithophel?", answer: "To have Absalom sleep with his father David's concubines publicly on the palace roof, showing all Israel he had irreversibly broken with him (2 Samuel 16:20-22)" },
  { id: 2082, category: "Absalom's Rebellion", prompt: "What counsel did Ahithophel advise against David?", answer: "To pursue David that same night with 12,000 men while he was weary and strike him down alone, ending the conflict quickly (2 Samuel 17:1-3)" },
  { id: 2083, category: "Absalom's Rebellion", prompt: "How did Hushai persuade Absalom to reject Ahithophel's advice?", answer: "He appealed to Absalom's pride, describing David as a fierce, enraged warrior likely lying in wait to ambush pursuers, and advised instead gathering a massive army and leading it personally (2 Samuel 17:7-13)" },
  { id: 2084, category: "Absalom's Rebellion", prompt: "How did David learn of Hushai's advice in time to escape across the Jordan?", answer: "Jonathan and Ahimaaz, the priests' sons, relayed it after hiding in a well at En-rogel, disguised with the help of a woman who covered the well with grain (2 Samuel 17:15-21)" },
  { id: 2085, category: "Absalom's Rebellion", prompt: "What did Ahithophel do after seeing his advice rejected in favor of Hushai's?", answer: "He went home, set his affairs in order, and hanged himself (2 Samuel 17:23)" },
  { id: 2086, category: "Absalom's Rebellion", prompt: "What command did David give his commanders regarding Absalom before the final battle?", answer: "To deal gently with the young man Absalom for his sake (2 Samuel 18:5)" },
  { id: 2087, category: "Absalom's Rebellion", prompt: "How did Absalom die?", answer: "His head/hair got caught in the branches of a great oak tree while riding his mule; Joab thrust three javelins into his heart despite David's order (2 Samuel 18:9-15)" },
  { id: 2088, category: "Absalom's Rebellion", prompt: "What was David's reaction upon hearing of Absalom's death?", answer: "He wept bitterly, crying \"O my son Absalom, my son, my son Absalom! Would I had died instead of you\" (2 Samuel 18:33)" },
  { id: 2089, category: "Absalom's Rebellion", prompt: "Why did Joab rebuke David after the battle, and what did he tell him to do?", answer: "David's excessive public mourning for Absalom was demoralizing the troops who had just saved his life and kingdom; Joab told him to go out and encourage them or the army would desert him (2 Samuel 19:5-8)" },
  { id: 2090, category: "Absalom's Rebellion", prompt: "Who was appointed over the army in David's return to power as an incentive to gain support from the tribe of Judah, and who murdered him soon after?", answer: "Amasa, Absalom's former general and David's nephew; Joab murdered him — stabbing him in the belly while pretending a friendly greeting — during Sheba's revolt (2 Samuel 19:13; 20:9-10)" },

  // ---------------- David's Later Reign (ch 21-24) ----------------
  { id: 2091, category: "David's Later Reign", prompt: "What did the LORD say caused a three-year famine in Israel during David's reign?", answer: "Saul's bloodguilt for killing the Gibeonites, breaking Israel's ancient oath to them (2 Samuel 21:1)" },
  { id: 2092, category: "David's Later Reign", prompt: "What atonement did the Gibeonites request from David for this bloodguilt?", answer: "Seven of Saul's male descendants to be handed over and executed before the LORD at Gibeah (2 Samuel 21:1-6)" },
  { id: 2093, category: "David's Later Reign", prompt: "Which of Saul's descendants did David spare from this judgment, and why?", answer: "Mephibosheth, because of David's oath to Jonathan (2 Samuel 21:7)" },
  { id: 2094, category: "David's Later Reign", prompt: "Who guarded the bodies of the executed men from birds and beasts for months, and what did David do once he learned of it?", answer: "Rizpah, mother of two of the men; moved by her vigil, David retrieved the bones of Saul and Jonathan and buried them properly along with the executed men (2 Samuel 21:10-14)", accepted: ["Rizpah kept watch; David then gave Saul and Jonathan a proper burial"] },
  { id: 2095, category: "David's Later Reign", prompt: "During renewed fighting with the Philistines, what happened to David personally that led his men to insist he no longer go into battle?", answer: "A Philistine giant, Ishbi-benob, nearly killed an exhausted David until Abishai came to his rescue (2 Samuel 21:15-17)" },
  { id: 2096, category: "David's Later Reign", prompt: "What is notable about David's song of praise recorded in 2 Samuel 22?", answer: "It closely parallels Psalm 18 (2 Samuel 22:1)", accepted: ["It's essentially the same song as Psalm 18"] },
  { id: 2097, category: "David's Later Reign", prompt: "What images does David use in his song of chapter 22 to describe God as his protector?", answer: "Rock, fortress, deliverer, shield, stronghold (2 Samuel 22:2-3)", accepted: ["Any two or three of: rock, fortress, shield, deliverer"] },
  { id: 2098, category: "David's Later Reign", prompt: "What image opens David's \"last words\" in chapter 23, describing a ruler who governs justly in the fear of God?", answer: "A just ruler is compared to morning light — like the sun rising on a cloudless morning (2 Samuel 23:3-4)" },
  { id: 2099, category: "David's Later Reign", prompt: "What did three of David's mighty men risk their lives to do for him, and how did David respond?", answer: "They broke through Philistine lines to draw water from the well of Bethlehem for him, but he refused to drink it, pouring it out to the LORD instead because it had cost them so dearly (2 Samuel 23:13-17)", accepted: ["Fetched water from the well of Bethlehem through enemy lines; David poured it out as an offering"] },
  { id: 2100, category: "David's Later Reign", prompt: "What sin does David commit in chapter 24, and how does he ultimately end the resulting plague?", answer: "He takes a census of the fighting men against Joab's advice; when a plague strikes as judgment, he buys the threshing floor of Araunah the Jebusite, builds an altar, and offers sacrifices there, refusing to offer God something that cost him nothing (2 Samuel 24:1-25)", accepted: ["Numbering the army; he buys Araunah's threshing floor and sacrifices there"] },

];
