// Bible Diagnostic Quiz — Matthew question bank
// 100 free-response questions covering the narrative arc of Matthew,
// grouped into 8 story sections (used as `category` for sampling and
// the results breakdown, same as the other question banks).
// Self-graded — the app reveals the accepted answer (and any accepted
// alternate phrasings) and the user marks their own typed answer
// correct or incorrect.
//
// Shape: { id, category, prompt, answer, accepted?: [alternate acceptable phrasings] }
//
// A few questions (word-for-word verse recall) deliberately put the
// chapter/verse reference in the prompt, since the reference is the
// setup for the exercise, not a hint toward the answer. Everywhere
// else, citations live in `answer` only.

const QUESTIONS_MATTHEW = [

  // ---------------- Birth & Preparation (ch 1-4) ----------------
  { id: 4001, category: "Birth & Preparation", prompt: "Matthew opens with a genealogy. As which two figures' descendant does its first verse specifically identify Jesus?", answer: "\"The son of David, the son of Abraham\" (Matthew 1:1)" },
  { id: 4002, category: "Birth & Preparation", prompt: "How does Matthew say his genealogy of Jesus is structured — into how many groups, of how many generations each?", answer: "Three groups of fourteen generations: Abraham to David, David to the exile to Babylon, and the exile to the Christ (Matthew 1:17)" },
  { id: 4003, category: "Birth & Preparation", prompt: "Matthew's genealogy is unusual for naming several women. Which women (other than Mary) are named in it?", answer: "Tamar, Rahab, Ruth, and \"the wife of Uriah\" (Bathsheba) (Matthew 1:3-6)", accepted: ["Tamar, Rahab, Ruth, Bathsheba"] },
  { id: 4004, category: "Birth & Preparation", prompt: "When Joseph learns Mary is pregnant, what does he decide to do before an angel appears to him in a dream?", answer: "Divorce her quietly, since he was a just man and unwilling to put her to shame (Matthew 1:19)", accepted: ["Send her away / break the engagement quietly"] },
  { id: 4005, category: "Birth & Preparation", prompt: "The angel tells Joseph to name the child Jesus. What reason does the angel give for that name?", answer: "\"For he will save his people from their sins\" (Matthew 1:21)" },
  { id: 4006, category: "Birth & Preparation", prompt: "Where do the wise men (magi) come from, and what leads them to Jerusalem looking for the newborn king?", answer: "From the east; they had seen his star when it rose and came to worship him (Matthew 2:1-2)" },
  { id: 4007, category: "Birth & Preparation", prompt: "What three gifts do the wise men present to the child?", answer: "Gold, frankincense, and myrrh (Matthew 2:11)" },
  { id: 4008, category: "Birth & Preparation", prompt: "When Herod realizes the wise men have not returned to him, what does he order?", answer: "The killing of all male children in Bethlehem and its region who were two years old or under (Matthew 2:16)" },
  { id: 4009, category: "Birth & Preparation", prompt: "Warned in dreams, where does Joseph take the family to escape Herod, and where do they settle after returning to Israel?", answer: "They flee to Egypt, then settle in Nazareth in Galilee (Matthew 2:13-14, 22-23)" },
  { id: 4010, category: "Birth & Preparation", prompt: "Describe John the Baptist as Matthew introduces him — where he preaches, his core message, and how he dresses and eats.", answer: "In the wilderness of Judea; \"Repent, for the kingdom of heaven is at hand\"; clothed in camel's hair with a leather belt, eating locusts and wild honey (Matthew 3:1-4)" },
  { id: 4011, category: "Birth & Preparation", prompt: "At Jesus' baptism, what does the voice from heaven say, and what accompanies it?", answer: "\"This is my beloved Son, with whom I am well pleased\"; the heavens open and the Spirit of God descends like a dove (Matthew 3:16-17)" },
  { id: 4012, category: "Birth & Preparation", prompt: "In the wilderness temptation, how long does Jesus fast, how many times does the devil test him, and how does Jesus answer each time?", answer: "Forty days and forty nights; three temptations (stones to bread, the pinnacle of the temple, the kingdoms of the world); each answered \"It is written...,\" quoting Deuteronomy (Matthew 4:1-11)" },
  { id: 4013, category: "Birth & Preparation", prompt: "Who are the first four disciples Jesus calls beside the Sea of Galilee, and what were they doing?", answer: "Simon Peter and his brother Andrew (casting a net), then James and John, the sons of Zebedee (mending nets in the boat) (Matthew 4:18-22)" },

  // ---------------- The Sermon on the Mount (ch 5-7) ----------------
  { id: 4014, category: "The Sermon on the Mount", prompt: "Recall at least one of the first seven Beatitudes (Matthew 5:3-9): give the \"Blessed are...\" group and the promise attached to it.", answer: "Any one of: the poor in spirit — theirs is the kingdom of heaven; those who mourn — they shall be comforted; the meek — they shall inherit the earth; those who hunger and thirst for righteousness — they shall be satisfied; the merciful — they shall receive mercy; the pure in heart — they shall see God; the peacemakers — they shall be called sons of God (Matthew 5:3-9)" },
  { id: 4015, category: "The Sermon on the Mount", prompt: "Recall at least one of the last two Beatitudes (Matthew 5:10-12), which turn to persecution.", answer: "Either: \"Blessed are those who are persecuted for righteousness' sake, for theirs is the kingdom of heaven\" (5:10); or \"Blessed are you when others revile you and persecute you and utter all kinds of evil against you falsely on my account. Rejoice and be glad, for your reward is great in heaven...\" (5:11-12)" },
  { id: 4016, category: "The Sermon on the Mount", prompt: "Jesus says he did not come to abolish the Law and the Prophets. What did he come to do with them?", answer: "To fulfill them (Matthew 5:17)" },
  { id: 4017, category: "The Sermon on the Mount", prompt: "In the antitheses (\"You have heard... but I say to you...\"), to what long-standing commandment does Jesus connect being angry with a brother?", answer: "\"You shall not murder\" — anger and contempt put a person in danger of judgment (Matthew 5:21-22)" },
  { id: 4018, category: "The Sermon on the Mount", prompt: "How does Jesus tell his hearers to respond to \"an eye for an eye\" — to someone who slaps them, sues them, or forces them to go a mile?", answer: "Do not resist the one who is evil: turn the other cheek, give your cloak as well, go the second mile (Matthew 5:38-41)" },
  { id: 4019, category: "The Sermon on the Mount", prompt: "Jesus replaces \"love your neighbor and hate your enemy\" with what command?", answer: "\"Love your enemies and pray for those who persecute you\" (Matthew 5:44)" },
  { id: 4020, category: "The Sermon on the Mount", prompt: "Word-for-word (ESV): give the Lord's Prayer as Jesus teaches it, Matthew 6:9-13.", answer: "\"Our Father in heaven, hallowed be your name. Your kingdom come, your will be done, on earth as it is in heaven. Give us this day our daily bread, and forgive us our debts, as we also have forgiven our debtors. And lead us not into temptation, but deliver us from evil.\" (Matthew 6:9-13; the ESV places \"For yours is the kingdom...\" only in a footnote)" },
  { id: 4021, category: "The Sermon on the Mount", prompt: "\"No one can serve two masters.\" What are the two masters Jesus names?", answer: "God and money (\"mammon\") (Matthew 6:24)" },
  { id: 4022, category: "The Sermon on the Mount", prompt: "What two examples from nature does Jesus use to tell his hearers not to be anxious about food and clothing?", answer: "The birds of the air (fed by the Father) and the lilies of the field (clothed more gloriously than Solomon) (Matthew 6:26-29)" },
  { id: 4023, category: "The Sermon on the Mount", prompt: "Complete Jesus' teaching: \"But seek first the kingdom of God and his righteousness, and...\"", answer: "\"...all these things will be added to you\" (Matthew 6:33)" },
  { id: 4024, category: "The Sermon on the Mount", prompt: "In the teaching on judging others, what does Jesus say you must deal with before helping with the speck in your brother's eye?", answer: "The log (beam) in your own eye (Matthew 7:3-5)" },
  { id: 4025, category: "The Sermon on the Mount", prompt: "Word-for-word (ESV): give the Golden Rule, Matthew 7:12.", answer: "\"So whatever you wish that others would do to you, do also to them, for this is the Law and the Prophets.\" (Matthew 7:12)" },
  { id: 4026, category: "The Sermon on the Mount", prompt: "Jesus contrasts two gates and two ways. Which one leads to life, and how does he describe it?", answer: "The narrow gate and the hard way — and \"those who find it are few\" (Matthew 7:13-14)" },
  { id: 4027, category: "The Sermon on the Mount", prompt: "The Sermon ends with a parable of two builders. What one thing separates the wise builder from the foolish one?", answer: "The wise builder hears these words of Jesus and does them (house on the rock); the foolish one hears and does not do them (house on the sand) (Matthew 7:24-27)" },

  // ---------------- Miracles & the Call to Follow (ch 8-10) ----------------
  { id: 4028, category: "Miracles & the Call to Follow", prompt: "What does the centurion at Capernaum say about his servant's healing that draws Jesus' praise, and what does Jesus say about his faith?", answer: "\"Only say the word, and my servant will be healed\" (he felt unworthy to have Jesus under his roof); Jesus says he has not found such faith in anyone in Israel (Matthew 8:8-10)" },
  { id: 4029, category: "Miracles & the Call to Follow", prompt: "Complete Jesus' reply to a would-be follower: \"Foxes have holes, and birds of the air have nests, but...\"", answer: "\"...the Son of Man has nowhere to lay his head\" (Matthew 8:20)" },
  { id: 4030, category: "Miracles & the Call to Follow", prompt: "When the disciples wake Jesus during the storm on the lake, what does he say to them before calming it?", answer: "\"Why are you afraid, O you of little faith?\" — then he rebukes the winds and the sea, and there is a great calm (Matthew 8:26)" },
  { id: 4031, category: "Miracles & the Call to Follow", prompt: "After Jesus casts the demons out of the men in the country of the Gadarenes, where do the demons go, and what happens?", answer: "Into a herd of pigs, which rush down the steep bank into the sea and drown (Matthew 8:30-32)" },
  { id: 4032, category: "Miracles & the Call to Follow", prompt: "When a paralyzed man is brought to Jesus, what does Jesus say first — the statement the scribes consider blasphemy?", answer: "\"Take heart, my son; your sins are forgiven\" (Matthew 9:2)" },
  { id: 4033, category: "Miracles & the Call to Follow", prompt: "What was Matthew doing when Jesus called him, and what did the Pharisees object to afterward?", answer: "Sitting at the tax booth; they objected that Jesus ate with tax collectors and sinners (Matthew 9:9-11)" },
  { id: 4034, category: "Miracles & the Call to Follow", prompt: "Complete Jesus' answer to that objection: \"Those who are well have no need of a physician, but those who are sick... I came not to call the righteous, but...\"", answer: "\"...sinners\" (Matthew 9:12-13)" },
  { id: 4035, category: "Miracles & the Call to Follow", prompt: "The woman healed by touching the fringe of Jesus' garment — how long had she been suffering, and from what?", answer: "A discharge of blood for twelve years (Matthew 9:20)" },
  { id: 4036, category: "Miracles & the Call to Follow", prompt: "At the house of the ruler whose daughter had died, what does Jesus say about the girl, and how does the crowd react?", answer: "\"The girl is not dead but sleeping\"; they laugh at him (Matthew 9:24)" },
  { id: 4037, category: "Miracles & the Call to Follow", prompt: "Complete the saying: \"The harvest is plentiful, but the...\" — and what does Jesus tell the disciples to do about it?", answer: "\"...laborers are few\"; pray earnestly to the Lord of the harvest to send out laborers (Matthew 9:37-38)" },
  { id: 4038, category: "Miracles & the Call to Follow", prompt: "What does Jesus tell the Twelve to take (or not take) for their journey when he sends them out?", answer: "No gold, silver, or copper; no bag, no extra tunic, sandals, or staff — \"the laborer deserves his food\" (Matthew 10:9-10)" },
  { id: 4039, category: "Miracles & the Call to Follow", prompt: "Complete the instruction: \"Behold, I am sending you out as sheep in the midst of wolves, so be...\"", answer: "\"...wise as serpents and innocent as doves\" (Matthew 10:16)" },
  { id: 4040, category: "Miracles & the Call to Follow", prompt: "Complete Jesus' teaching on the cost of discipleship: \"Whoever loves father or mother more than me is not worthy of me... and whoever does not...\"", answer: "\"...take his cross and follow me is not worthy of me\" (Matthew 10:37-38)" },

  // ---------------- Opposition & Kingdom Parables (ch 11-13) ----------------
  { id: 4041, category: "Opposition & Kingdom Parables", prompt: "From prison, John the Baptist sends his disciples to ask Jesus what question?", answer: "\"Are you the one who is to come, or shall we look for another?\" (Matthew 11:2-3)" },
  { id: 4042, category: "Opposition & Kingdom Parables", prompt: "How does Jesus answer John's question — what evidence does he point to?", answer: "\"The blind receive their sight and the lame walk, lepers are cleansed and the deaf hear, and the dead are raised up, and the poor have good news preached to them\" (Matthew 11:4-5)" },
  { id: 4043, category: "Opposition & Kingdom Parables", prompt: "Complete the invitation: \"Come to me, all who labor and are heavy laden, and I will give you ___. Take my ___ upon you...\"", answer: "\"...rest\"; \"...yoke\" — \"for my yoke is easy, and my burden is light\" (Matthew 11:28-30)" },
  { id: 4044, category: "Opposition & Kingdom Parables", prompt: "When the Pharisees challenge his disciples for plucking grain on the Sabbath, what does Jesus say the Son of Man is?", answer: "\"Lord of the Sabbath\" (he also cites David eating the bread of the Presence) (Matthew 12:1-8)" },
  { id: 4045, category: "Opposition & Kingdom Parables", prompt: "When accused of casting out demons by Beelzebul, what is the core of Jesus' rebuttal?", answer: "\"Every kingdom divided against itself is laid waste\" — Satan would not cast out Satan (Matthew 12:25-26)" },
  { id: 4046, category: "Opposition & Kingdom Parables", prompt: "What does Jesus say is the one sin that \"will not be forgiven\"?", answer: "Blasphemy against the Holy Spirit (Matthew 12:31-32)" },
  { id: 4047, category: "Opposition & Kingdom Parables", prompt: "What is the only \"sign\" Jesus says will be given to \"an evil and adulterous generation,\" and what does he say it points to?", answer: "The sign of the prophet Jonah — as Jonah was three days and nights in the fish, so the Son of Man will be three days and nights \"in the heart of the earth\" (Matthew 12:39-40)" },
  { id: 4048, category: "Opposition & Kingdom Parables", prompt: "Told that his mother and brothers are outside, how does Jesus define his true family?", answer: "\"Whoever does the will of my Father in heaven is my brother and sister and mother\" (Matthew 12:48-50)" },
  { id: 4049, category: "Opposition & Kingdom Parables", prompt: "In the parable of the sower, what does Jesus say the seed sown among thorns represents?", answer: "One who hears the word, but \"the cares of the world and the deceitfulness of riches choke the word,\" and it proves unfruitful (Matthew 13:22)" },
  { id: 4050, category: "Opposition & Kingdom Parables", prompt: "In the parable of the weeds among the wheat, what does the master tell his servants to do about the weeds, and why?", answer: "Let both grow together until the harvest, so that pulling the weeds doesn't uproot the wheat; at harvest the weeds are gathered and burned (Matthew 13:28-30)" },
  { id: 4051, category: "Opposition & Kingdom Parables", prompt: "Two short parables compare the kingdom of heaven to a tiny or hidden thing that grows or spreads. What are the two images?", answer: "A mustard seed (smallest of seeds, grows into a tree) and leaven (hidden in flour until it is all leavened) (Matthew 13:31-33)" },
  { id: 4052, category: "Opposition & Kingdom Parables", prompt: "In the twin parables of the hidden treasure and the pearl of great value, what does the finder do in each case?", answer: "Sells all that he has and buys the field / the pearl (Matthew 13:44-46)" },
  { id: 4053, category: "Opposition & Kingdom Parables", prompt: "How do the people of Jesus' hometown react to his teaching, and what does Jesus say a prophet lacks honor in?", answer: "They take offense — \"Is this not the carpenter's son?\"; a prophet is not without honor \"except in his hometown and in his own household\" (Matthew 13:54-57)" },

  // ---------------- Bread, Confession & the Community (ch 14-18) ----------------
  { id: 4054, category: "Bread, Confession & the Community", prompt: "How does John the Baptist die in Matthew's account?", answer: "Herod has him beheaded in prison — the daughter of Herodias dances at Herod's birthday, and prompted by her mother asks for John's head on a platter; Herod grants it because of his oath (Matthew 14:6-11)" },
  { id: 4055, category: "Bread, Confession & the Community", prompt: "At the feeding of the five thousand, how much food does Jesus start with, and how much is left over?", answer: "Five loaves and two fish; twelve baskets of broken pieces left over (about five thousand men ate, besides women and children) (Matthew 14:17-21)" },
  { id: 4056, category: "Bread, Confession & the Community", prompt: "Matthew alone records that one disciple also walked on the water toward Jesus. Who was it, and why did he begin to sink?", answer: "Peter; he saw the wind, was afraid, and doubted — Jesus caught him: \"O you of little faith, why did you doubt?\" (Matthew 14:29-31)" },
  { id: 4057, category: "Bread, Confession & the Community", prompt: "In the dispute over eating with unwashed hands, what does Jesus say actually defiles a person?", answer: "Not what goes into the mouth, but what comes out of it — what comes from the heart (evil thoughts, murder, adultery, slander, etc.) (Matthew 15:10-20)" },
  { id: 4058, category: "Bread, Confession & the Community", prompt: "In the exchange with the Canaanite woman about \"the children's bread\" and \"the dogs,\" how does she reply, and how does Jesus respond?", answer: "\"Even the dogs eat the crumbs that fall from their masters' table\"; Jesus says, \"O woman, great is your faith! Be it done for you as you desire\" (Matthew 15:26-28)" },
  { id: 4059, category: "Bread, Confession & the Community", prompt: "At Caesarea Philippi, Jesus asks who people say he is, then who the disciples say he is. What is Peter's answer?", answer: "\"You are the Christ, the Son of the living God\" (people had said John the Baptist, Elijah, Jeremiah, or one of the prophets) (Matthew 16:13-16)" },
  { id: 4060, category: "Bread, Confession & the Community", prompt: "How does Jesus respond to Peter's confession — what does he say about the rock, the church, and the keys?", answer: "\"On this rock I will build my church, and the gates of hell shall not prevail against it\"; he gives Peter \"the keys of the kingdom of heaven,\" with authority to bind and loose (Matthew 16:18-19)" },
  { id: 4061, category: "Bread, Confession & the Community", prompt: "Right after praising Peter, Jesus rebukes him sharply. What does he say, and what prompted it?", answer: "\"Get behind me, Satan! You are a hindrance to me\" — because Peter objected to Jesus' prediction that he must suffer, be killed, and be raised (Matthew 16:21-23)" },
  { id: 4062, category: "Bread, Confession & the Community", prompt: "At the Transfiguration, who appears talking with Jesus, and what does the voice from the cloud say?", answer: "Moses and Elijah; \"This is my beloved Son, with whom I am well pleased; listen to him\" (Matthew 17:1-5)" },
  { id: 4063, category: "Bread, Confession & the Community", prompt: "Matthew alone tells how Jesus provides the temple tax for himself and Peter. How?", answer: "Peter is to cast a hook, and in the mouth of the first fish he catches he will find a shekel to pay the tax for them both (Matthew 17:24-27)" },
  { id: 4064, category: "Bread, Confession & the Community", prompt: "In the discourse on the church, what steps does Jesus lay out for dealing with a brother who sins against you?", answer: "Tell him his fault privately; if he won't listen, take one or two others; then tell it to the church; if he still refuses, treat him as a Gentile and a tax collector (Matthew 18:15-17)" },
  { id: 4065, category: "Bread, Confession & the Community", prompt: "When Peter asks how many times he must forgive a brother, what does he suggest, and what does Jesus answer?", answer: "Peter suggests seven times; Jesus says \"seventy-seven times\" (or seventy times seven) (Matthew 18:21-22)" },
  { id: 4066, category: "Bread, Confession & the Community", prompt: "In the parable of the unforgiving servant, what is the contrast between the two debts, and what is the lesson?", answer: "He is forgiven an enormous debt (ten thousand talents) but jails a fellow servant over a small one (a hundred denarii); God will likewise deal with those who won't forgive their brother from the heart (Matthew 18:23-35)" },

  // ---------------- The Road to Jerusalem & Confrontation (ch 19-23) ----------------
  { id: 4067, category: "The Road to Jerusalem & Confrontation", prompt: "In the debate over divorce, what does Jesus say Moses permitted, and why — and what exception does Jesus give?", answer: "Moses allowed a certificate of divorce \"because of your hardness of heart,\" but it was not so from the beginning; divorce and remarriage is adultery \"except for sexual immorality\" (Matthew 19:7-9)" },
  { id: 4068, category: "The Road to Jerusalem & Confrontation", prompt: "Complete the saying: \"Let the little children come to me and do not hinder them, for...\"", answer: "\"...to such belongs the kingdom of heaven\" (Matthew 19:14)" },
  { id: 4069, category: "The Road to Jerusalem & Confrontation", prompt: "What does Jesus tell the rich young man he still lacks, and what famous comparison follows about wealth?", answer: "\"Go, sell what you possess and give to the poor... and come, follow me\"; \"it is easier for a camel to go through the eye of a needle than for a rich person to enter the kingdom of God\" (Matthew 19:21-24)" },
  { id: 4070, category: "The Road to Jerusalem & Confrontation", prompt: "In the parable of the laborers in the vineyard, what is the workers' complaint, and what point does the landowner make?", answer: "Those hired first are paid the same denarius as those hired last and grumble; the owner may do as he chooses with what is his — \"the last will be first, and the first last\" (Matthew 20:1-16)" },
  { id: 4071, category: "The Road to Jerusalem & Confrontation", prompt: "What request does the mother of James and John bring to Jesus?", answer: "That her two sons be seated at Jesus' right hand and left hand in his kingdom (Matthew 20:20-21)" },
  { id: 4072, category: "The Road to Jerusalem & Confrontation", prompt: "Complete the saying: \"The Son of Man came not to be served but to serve, and to give his life as a...\"", answer: "\"...ransom for many\" (Matthew 20:28)" },
  { id: 4073, category: "The Road to Jerusalem & Confrontation", prompt: "As Jesus enters Jerusalem, what do the crowds shout, and what do they spread on the road?", answer: "\"Hosanna to the Son of David! Blessed is he who comes in the name of the Lord!\"; they spread cloaks and branches cut from trees on the road (Matthew 21:8-9)" },
  { id: 4074, category: "The Road to Jerusalem & Confrontation", prompt: "When Jesus drives out those buying and selling in the temple, what does he say they have made it?", answer: "\"My house shall be called a house of prayer, but you make it a den of robbers\" (Matthew 21:13)" },
  { id: 4075, category: "The Road to Jerusalem & Confrontation", prompt: "What does Jesus do to the fig tree, and what lesson about faith does he draw from it?", answer: "He curses the fruitless fig tree and it withers at once; with faith and no doubt, \"you will say to this mountain, 'Be taken up and thrown into the sea,' and it will happen\" (Matthew 21:19-21)" },
  { id: 4076, category: "The Road to Jerusalem & Confrontation", prompt: "In the parable of the tenants, what do the tenants do to the owner's servants and finally his son, and what does Jesus say will happen as a result?", answer: "They beat and kill the servants, then kill the son to seize the inheritance; \"the kingdom of God will be taken away from you and given to a people producing its fruits\" (Matthew 21:33-43)" },
  { id: 4077, category: "The Road to Jerusalem & Confrontation", prompt: "When asked whether it is lawful to pay taxes to Caesar, how does Jesus answer?", answer: "Shown a denarius with Caesar's image: \"Render to Caesar the things that are Caesar's, and to God the things that are God's\" (Matthew 22:21)" },
  { id: 4078, category: "The Road to Jerusalem & Confrontation", prompt: "What does Jesus name as the greatest commandment, and the second like it — and what does he say hangs on them?", answer: "Love the Lord your God with all your heart, soul, and mind; and love your neighbor as yourself; \"On these two commandments depend all the Law and the Prophets\" (Matthew 22:37-40)" },
  { id: 4079, category: "The Road to Jerusalem & Confrontation", prompt: "In the woes of Matthew 23, what does Jesus repeatedly call the scribes and Pharisees, and what vivid image compares them to something clean outside but full of death inside?", answer: "\"Hypocrites\" and \"blind guides\"; he calls them \"whitewashed tombs\" — beautiful outside, full of dead people's bones within (Matthew 23:13-28)" },

  // ---------------- The Olivet Discourse (ch 24-25) ----------------
  { id: 4080, category: "The Olivet Discourse", prompt: "What does Jesus predict about the temple buildings that prompts the disciples' questions on the Mount of Olives?", answer: "\"There will not be left here one stone upon another that will not be thrown down\" (Matthew 24:2)" },
  { id: 4081, category: "The Olivet Discourse", prompt: "What do the disciples ask Jesus privately on the Mount of Olives?", answer: "\"When will these things be, and what will be the sign of your coming and of the end of the age?\" (Matthew 24:3)" },
  { id: 4082, category: "The Olivet Discourse", prompt: "What does Jesus list as things that will happen but are only \"the beginning of the birth pains,\" not yet the end?", answer: "False christs, wars and rumors of wars, famines and earthquakes in various places, persecution, and the gospel proclaimed to all nations (Matthew 24:4-14)" },
  { id: 4083, category: "The Olivet Discourse", prompt: "What does Jesus say about who knows \"that day and hour\"?", answer: "\"No one knows, not even the angels of heaven, nor the Son, but the Father only\" (Matthew 24:36)" },
  { id: 4084, category: "The Olivet Discourse", prompt: "\"As were the days of ___, so will be the coming of the Son of Man.\" Whose days, and what were people doing?", answer: "The days of Noah — eating, drinking, marrying and giving in marriage, unaware until the flood came and swept them away (Matthew 24:37-39)" },
  { id: 4085, category: "The Olivet Discourse", prompt: "In the parable of the ten virgins, what separates the wise from the foolish, and what is the closing lesson?", answer: "The wise bring extra oil for their lamps and are ready when the bridegroom comes; \"Watch therefore, for you know neither the day nor the hour\" (Matthew 25:1-13)" },
  { id: 4086, category: "The Olivet Discourse", prompt: "In the parable of the talents, how are the amounts distributed, and what happens to the servant who received one talent?", answer: "Five, two, and one talent, \"each according to his ability\"; the one who buried his talent has it taken away and is cast into the outer darkness (Matthew 25:14-30)" },
  { id: 4087, category: "The Olivet Discourse", prompt: "In the judgment of the sheep and the goats, on what basis are the two groups separated, and what is the King's refrain?", answer: "On how they treated \"the least of these\" — feeding the hungry, welcoming the stranger, clothing the naked, visiting the sick and imprisoned; \"as you did it to one of the least of these my brothers, you did it to me\" (Matthew 25:31-46)" },

  // ---------------- Passion & Resurrection (ch 26-28) ----------------
  { id: 4088, category: "Passion & Resurrection", prompt: "At Bethany a woman pours expensive ointment on Jesus' head. What is the objection, and how does Jesus defend her act?", answer: "The disciples call it a waste that could have been sold for the poor; Jesus says she has done a beautiful thing and has prepared him for burial — \"wherever this gospel is proclaimed... what she has done will be told in memory of her\" (Matthew 26:6-13)" },
  { id: 4089, category: "Passion & Resurrection", prompt: "What do the chief priests pay Judas to betray Jesus?", answer: "Thirty pieces of silver (Matthew 26:14-15)" },
  { id: 4090, category: "Passion & Resurrection", prompt: "At the Last Supper, what does Jesus say as he gives the bread and then the cup?", answer: "\"Take, eat; this is my body\"; \"this is my blood of the covenant, which is poured out for many for the forgiveness of sins\" (Matthew 26:26-28)" },
  { id: 4091, category: "Passion & Resurrection", prompt: "In Gethsemane, what does Jesus pray, and what does he find the disciples doing?", answer: "\"My Father, if it be possible, let this cup pass from me; nevertheless, not as I will, but as you will\"; he finds the disciples sleeping — \"could you not watch with me one hour?\" (Matthew 26:39-40)" },
  { id: 4092, category: "Passion & Resurrection", prompt: "How does Judas identify Jesus to the arresting party, and what does Jesus say when a companion draws a sword and cuts off the servant's ear?", answer: "With a kiss (\"Greetings, Rabbi!\"); \"Put your sword back into its place. For all who take the sword will perish by the sword\" (Matthew 26:48-52)" },
  { id: 4093, category: "Passion & Resurrection", prompt: "At the trial before Caiaphas, what does the high priest demand under oath, and how does he react to Jesus' answer?", answer: "He adjures Jesus \"by the living God\" to say whether he is the Christ, the Son of God; when Jesus answers (\"you will see the Son of Man... coming on the clouds\"), the high priest tears his robes and charges blasphemy (Matthew 26:63-66)" },
  { id: 4094, category: "Passion & Resurrection", prompt: "How do Peter's denials end?", answer: "After denying Jesus three times, the rooster crows; Peter remembers Jesus' words and goes out and weeps bitterly (Matthew 26:74-75)" },
  { id: 4095, category: "Passion & Resurrection", prompt: "What does Judas do with the thirty pieces of silver, what happens to him, and what do the priests buy with the money?", answer: "He throws the silver into the temple and hangs himself; the priests use it to buy the potter's field as a burial place for strangers, called the Field of Blood (Matthew 27:3-8)" },
  { id: 4096, category: "Passion & Resurrection", prompt: "At Jesus' trial before Pilate, whom does the crowd choose to release instead of Jesus, what does Pilate do with water, and what does the crowd say?", answer: "Barabbas; Pilate washes his hands before the crowd (\"I am innocent of this man's blood\"); the people answer, \"His blood be on us and on our children!\" (Matthew 27:15-26)" },
  { id: 4097, category: "Passion & Resurrection", prompt: "What does Matthew record happening at the moment of Jesus' death, and what does the centurion say?", answer: "The temple curtain is torn in two from top to bottom, the earth shakes, rocks split, and tombs are opened; the centurion and those with him say, \"Truly this was the Son of God!\" (Matthew 27:51-54)" },
  { id: 4098, category: "Passion & Resurrection", prompt: "On the first day of the week, who comes to the tomb, and what does the angel tell them?", answer: "Mary Magdalene and \"the other Mary\"; an angel has rolled back the stone and says, \"He is not here, for he has risen, as he said\" — go and tell the disciples he is going ahead to Galilee (Matthew 28:1-7)" },
  { id: 4099, category: "Passion & Resurrection", prompt: "What story do the chief priests pay the tomb guards to spread?", answer: "That the disciples came by night and stole the body while the guards were asleep (Matthew 28:12-15)" },
  { id: 4100, category: "Passion & Resurrection", prompt: "Word-for-word (ESV): give the Great Commission, Matthew 28:19-20.", answer: "\"Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all that I have commanded you. And behold, I am with you always, to the end of the age.\" (Matthew 28:19-20)" },

];
