// Bible Diagnostic Quiz — question bank
// 100 questions across 8 categories covering themes, book content, and famous verses.
// Verse quotations are from the ESV® Bible (see index.html footer for required attribution).
//
// Shape: { id, category, question, options: [4 strings], answer: index of correct option }

const QUESTIONS = [

  // ---------------- Pentateuch (Genesis–Deuteronomy) ----------------
  { id: 1, category: "Pentateuch", question: "According to Genesis 1, on which day did God create land animals and humans?", options: ["Day 4", "Day 5", "Day 6", "Day 7"], answer: 2 },
  { id: 2, category: "Pentateuch", question: "What covenant sign did God give Noah after the flood?", options: ["Circumcision", "The rainbow", "Passover", "The Sabbath"], answer: 1 },
  { id: 3, category: "Pentateuch", question: "God changed Abram's name to Abraham as part of a covenant promising he would be the father of:", options: ["One great nation", "A multitude of nations", "The priesthood alone", "The kings of Israel only"], answer: 1 },
  { id: 4, category: "Pentateuch", question: "Which of Jacob's sons was sold into slavery by his brothers and rose to power in Egypt?", options: ["Reuben", "Judah", "Joseph", "Benjamin"], answer: 2 },
  { id: 5, category: "Pentateuch", question: "The book of Exodus centers on God delivering Israel from slavery in Egypt through:", options: ["A civil war", "Moses and the plagues", "A trade agreement", "The prophet Elijah"], answer: 1 },
  { id: 6, category: "Pentateuch", question: "The Ten Commandments were given to Moses at:", options: ["Mount Carmel", "Mount Sinai", "Mount Nebo", "Mount Zion"], answer: 1 },
  { id: 7, category: "Pentateuch", question: "The book of Leviticus is primarily concerned with:", options: ["The conquest of Canaan", "Laws on holiness, sacrifice, and worship for Israel", "The reign of King David", "Genealogies of the twelve tribes"], answer: 1 },
  { id: 8, category: "Pentateuch", question: "In Numbers, why did the generation that left Egypt wander in the wilderness for 40 years?", options: ["They got lost", "Unbelief after the report of the twelve spies", "They waited for the tabernacle to be built", "A famine in Canaan"], answer: 1 },
  { id: 9, category: "Pentateuch", question: "Deuteronomy is largely structured as:", options: ["A collection of psalms", "Moses' farewell speeches restating the law to a new generation", "A legal code written by Joshua", "A history of the judges"], answer: 1 },
  { id: 10, category: "Pentateuch", question: "Which of these is NOT one of the Ten Commandments?", options: ["You shall not murder", "You shall not steal", "You shall love your neighbor as yourself", "You shall not covet"], answer: 2 },
  { id: 11, category: "Pentateuch", question: "Complete the verse: 'In the beginning, God created the heavens and ___.' (Genesis 1:1)", options: ["the earth", "the stars", "mankind", "the seas"], answer: 0 },
  { id: 12, category: "Pentateuch", question: "The Passover meal, instituted in Exodus 12, commemorates:", options: ["The crossing of the Red Sea", "The final plague and Israel's deliverance from Egypt", "The giving of the Ten Commandments", "The building of the tabernacle"], answer: 1 },

  // ---------------- Historical Books (Joshua–Esther) ----------------
  { id: 13, category: "Historical Books", question: "Under whose leadership did Israel cross the Jordan and enter the Promised Land?", options: ["Moses", "Joshua", "Caleb", "Aaron"], answer: 1 },
  { id: 14, category: "Historical Books", question: "The book of Judges describes a repeating cycle of:", options: ["Israel's sin, oppression, crying out, and deliverance by a judge", "Kings rising and falling", "Priests offering sacrifices", "Prophets confronting Pharaoh"], answer: 0 },
  { id: 15, category: "Historical Books", question: "Ruth, a Moabite widow, is notable for being an ancestor of which king?", options: ["Saul", "David", "Solomon", "Hezekiah"], answer: 1 },
  { id: 16, category: "Historical Books", question: "Who was Israel's first king, anointed by Samuel?", options: ["David", "Saul", "Solomon", "Samuel himself"], answer: 1 },
  { id: 17, category: "Historical Books", question: "David is most famous for defeating which Philistine giant?", options: ["Og", "Goliath", "Nabal", "Achish"], answer: 1 },
  { id: 18, category: "Historical Books", question: "Which king was known for his God-given wisdom and for building the first temple in Jerusalem?", options: ["Saul", "David", "Solomon", "Rehoboam"], answer: 2 },
  { id: 19, category: "Historical Books", question: "After Solomon's reign, the kingdom split into:", options: ["Three equal kingdoms", "The northern kingdom (Israel) and southern kingdom (Judah)", "A confederation of judges", "Roman provinces"], answer: 1 },
  { id: 20, category: "Historical Books", question: "Elijah and Elisha, prophets described in 1–2 Kings, are best known for:", options: ["Writing psalms", "Miraculous deeds confronting idolatry, especially Baal worship", "Leading military conquests", "Building the second temple"], answer: 1 },
  { id: 21, category: "Historical Books", question: "1–2 Chronicles largely retells the history of Israel's kings with special focus on:", options: ["The northern kingdom", "The Davidic line and temple worship", "The judges", "The start of the exile"], answer: 1 },
  { id: 22, category: "Historical Books", question: "Ezra and Nehemiah both deal with:", options: ["The conquest of Canaan", "The return of the Jewish exiles and rebuilding Jerusalem/the temple", "The reign of Solomon", "The start of the Babylonian exile"], answer: 1 },
  { id: 23, category: "Historical Books", question: "The book of Esther is unique among Old Testament books because it never directly mentions:", options: ["Persia", "God's name", "The Jewish people", "A king"], answer: 1 },
  { id: 24, category: "Historical Books", question: "What was Esther's role that allowed her to save the Jewish people from Haman's plot?", options: ["She was a prophetess", "She became queen of Persia", "She was a military commander", "She was Nehemiah's sister"], answer: 1 },

  // ---------------- Wisdom & Poetry (Job–Song of Solomon) ----------------
  { id: 25, category: "Wisdom & Poetry", question: "The book of Job wrestles primarily with the question of:", options: ["How to build the temple", "Why the righteous suffer", "How Israel should be governed", "The origin of sin"], answer: 1 },
  { id: 26, category: "Wisdom & Poetry", question: "At the end of Job, God responds to Job's suffering mainly by:", options: ["Explaining exactly why Job suffered", "Pointing to his own power and wisdom in creation", "Punishing Job's friends only", "Sending an angel to comfort him"], answer: 1 },
  { id: 27, category: "Wisdom & Poetry", question: "The book of Psalms is best described as:", options: ["A legal code", "A collection of songs and prayers of praise, lament, and trust", "A single continuous narrative", "Solomon's autobiography"], answer: 1 },
  { id: 28, category: "Wisdom & Poetry", question: "Complete the verse: 'The LORD is my shepherd; I shall not ___.' (Psalm 23:1)", options: ["fear", "want", "fall", "fail"], answer: 1 },
  { id: 29, category: "Wisdom & Poetry", question: "Proverbs, largely attributed to Solomon, focuses on:", options: ["Practical wisdom for godly living", "The end times", "The history of the kings", "Levitical law"], answer: 0 },
  { id: 30, category: "Wisdom & Poetry", question: "'Trust in the LORD with all your heart, and do not lean on your own understanding' comes from which book?", options: ["Psalms", "Proverbs", "Ecclesiastes", "Job"], answer: 1 },
  { id: 31, category: "Wisdom & Poetry", question: "The refrain 'Vanity of vanities... all is vanity' and the theme that life is fleeting without God is central to:", options: ["Ecclesiastes", "Lamentations", "Job", "Song of Solomon"], answer: 0 },
  { id: 32, category: "Wisdom & Poetry", question: "Song of Solomon (Song of Songs) is a poetic book centered on:", options: ["The wisdom of Solomon's reign", "Romantic and marital love", "The fall of Jerusalem", "Prophecies of a coming king"], answer: 1 },
  { id: 33, category: "Wisdom & Poetry", question: "Which Psalm begins 'Have mercy on me, O God, according to your steadfast love' and is traditionally linked to David's repentance after his sin with Bathsheba?", options: ["Psalm 1", "Psalm 23", "Psalm 51", "Psalm 119"], answer: 2 },
  { id: 34, category: "Wisdom & Poetry", question: "Psalm 119, the longest chapter in the Bible, is structured around praise for:", options: ["God's creation", "God's law/word", "The temple", "The Davidic covenant"], answer: 1 },
  { id: 35, category: "Wisdom & Poetry", question: "'For everything there is a season, and a time for every matter under heaven' is found in:", options: ["Psalms", "Proverbs", "Ecclesiastes", "Job"], answer: 2 },
  { id: 36, category: "Wisdom & Poetry", question: "Job's friends who come to comfort him ultimately argue that his suffering must be a result of:", options: ["Satan's direct attack", "Hidden sin on Job's part", "God's randomness", "A test everyone must face"], answer: 1 },

  // ---------------- Prophets (Isaiah–Malachi) ----------------
  { id: 37, category: "Prophets", question: "Isaiah's prophecy includes a passage Christians see as pointing to a coming Messiah called, among other titles:", options: ["'Wonderful Counselor, Mighty God'", "'Servant of the Law'", "'Prince of Priests'", "'Judge of Nations'"], answer: 0 },
  { id: 38, category: "Prophets", question: "Jeremiah is often called the 'weeping prophet' because he:", options: ["Was persecuted and grieved over Judah's coming judgment", "Lost his family in battle", "Wrote only laments", "Was blind"], answer: 0 },
  { id: 39, category: "Prophets", question: "Complete the verse: 'For I know the plans I have for you, declares the LORD, plans for welfare and not for evil, to give you a future and a ___.' (Jeremiah 29:11)", options: ["home", "hope", "blessing", "kingdom"], answer: 1 },
  { id: 40, category: "Prophets", question: "Lamentations mourns the destruction of:", options: ["Samaria", "Jerusalem and the temple", "Nineveh", "Babylon"], answer: 1 },
  { id: 41, category: "Prophets", question: "Ezekiel's vivid visions, including the valley of dry bones, are largely addressed to Israelites experiencing:", options: ["Victory in battle", "Exile in Babylon", "Famine in Egypt", "Persecution under Rome"], answer: 1 },
  { id: 42, category: "Prophets", question: "Daniel, taken into exile as a young man, is best known for surviving:", options: ["A flood", "A den of lions", "A shipwreck", "A plague"], answer: 1 },
  { id: 43, category: "Prophets", question: "The book of Hosea uses the prophet's own troubled marriage as a picture of:", options: ["Israel's unfaithfulness to God", "God's judgment on Egypt", "The exile in Babylon", "The coming Messiah's suffering"], answer: 0 },
  { id: 44, category: "Prophets", question: "Joel's prophecy about a locust plague ultimately points forward to:", options: ["The exile", "A future outpouring of God's Spirit", "The fall of Nineveh", "The rebuilding of the temple"], answer: 1 },
  { id: 45, category: "Prophets", question: "Amos, who prophesied to the northern kingdom, is known for his strong emphasis on:", options: ["Priestly ritual", "Social justice and righteousness", "The end of the exile", "The Davidic covenant"], answer: 1 },
  { id: 46, category: "Prophets", question: "Jonah is famous for being swallowed by a great fish after trying to flee from God's call to preach to:", options: ["Babylon", "Nineveh", "Egypt", "Tyre"], answer: 1 },
  { id: 47, category: "Prophets", question: "Micah 6:8 summarizes what God requires: to do justice, to love kindness, and to ___.", options: ["fear the LORD", "walk humbly with your God", "offer sacrifices", "keep the Sabbath"], answer: 1 },
  { id: 48, category: "Prophets", question: "Habakkuk is unusual among the prophets because much of the book is a:", options: ["Series of visions only", "Dialogue/complaint between the prophet and God", "Genealogy", "Legal code"], answer: 1 },
  { id: 49, category: "Prophets", question: "Malachi, the last book of the Old Testament, ends anticipating:", options: ["The Babylonian exile", "A coming messenger before 'the day of the LORD'", "The building of Solomon's temple", "The reign of David"], answer: 1 },

  // ---------------- Gospels (Matthew–John) ----------------
  { id: 50, category: "Gospels", question: "Matthew's Gospel was written especially to show Jesus as:", options: ["A Roman citizen", "The fulfillment of Jewish prophecy and promised Messiah/King", "A Greek philosopher", "An Essene teacher"], answer: 1 },
  { id: 51, category: "Gospels", question: "The Sermon on the Mount, including the Beatitudes, is recorded primarily in:", options: ["Matthew", "Mark", "Luke", "John"], answer: 0 },
  { id: 52, category: "Gospels", question: "Mark's Gospel is notable for its fast pace and its emphasis on Jesus as:", options: ["A suffering servant who acts decisively", "A philosopher-teacher", "A genealogical heir", "A lawgiver"], answer: 0 },
  { id: 53, category: "Gospels", question: "Luke's Gospel places special emphasis on Jesus' compassion toward:", options: ["Roman officials only", "The poor, outcasts, women, and sinners", "The Pharisees", "King Herod"], answer: 1 },
  { id: 54, category: "Gospels", question: "The parable of the Prodigal Son, illustrating God's grace toward repentant sinners, is found in:", options: ["Matthew", "Mark", "Luke", "John"], answer: 2 },
  { id: 55, category: "Gospels", question: "John's Gospel differs from the other three ('Synoptic') Gospels by focusing heavily on:", options: ["Parables about the kingdom", "Jesus' identity as the divine Son of God through 'I am' statements and signs", "Jesus' genealogy", "A strict chronological list of miracles"], answer: 1 },
  { id: 56, category: "Gospels", question: "Complete the verse: 'For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have ___.' (John 3:16)", options: ["peace", "eternal life", "forgiveness", "joy"], answer: 1 },
  { id: 57, category: "Gospels", question: "At Jesus' baptism by John the Baptist, what happened?", options: ["Fire fell and there was silence", "The Holy Spirit descended like a dove, and the Father's voice spoke", "An angel appeared with a trumpet", "Lightning and thunder struck"], answer: 1 },
  { id: 58, category: "Gospels", question: "Jesus' first recorded miracle in John's Gospel was:", options: ["Healing a blind man", "Turning water into wine at Cana", "Calming a storm", "Raising Lazarus"], answer: 1 },
  { id: 59, category: "Gospels", question: "The Last Supper, where Jesus instituted what Christians call Communion, took place during which Jewish feast?", options: ["Yom Kippur", "Passover", "Pentecost", "Feast of Tabernacles"], answer: 1 },
  { id: 60, category: "Gospels", question: "Who betrayed Jesus to the religious authorities for thirty pieces of silver?", options: ["Peter", "Judas Iscariot", "Thomas", "Caiaphas"], answer: 1 },
  { id: 61, category: "Gospels", question: "According to all four Gospels, on which day after the crucifixion did Jesus rise from the dead?", options: ["The first day", "The third day", "The seventh day", "The fortieth day"], answer: 1 },
  { id: 62, category: "Gospels", question: "The Great Commission, Jesus' command to 'go and make disciples of all nations,' closes out which Gospel?", options: ["Mark", "Luke", "Matthew", "John"], answer: 2 },

  // ---------------- Acts & Early Church ----------------
  { id: 63, category: "Acts & Early Church", question: "The book of Acts, written by the same author as Luke's Gospel, primarily narrates:", options: ["Jesus' teachings", "The spread of the early church from Jerusalem outward through the Holy Spirit", "The fall of Jerusalem", "Paul's letters"], answer: 1 },
  { id: 64, category: "Acts & Early Church", question: "On the day of Pentecost in Acts 2, what dramatic event empowered the apostles to preach?", options: ["A vision of angels", "The Holy Spirit coming with sound like wind and tongues of fire", "An earthquake", "A voice from a burning bush"], answer: 1 },
  { id: 65, category: "Acts & Early Church", question: "Who was the first Christian martyr recorded in Acts, stoned for his testimony?", options: ["James", "Stephen", "Barnabas", "Timothy"], answer: 1 },
  { id: 66, category: "Acts & Early Church", question: "Saul of Tarsus, a persecutor of Christians, was dramatically converted on the road to:", options: ["Jerusalem", "Damascus", "Rome", "Antioch"], answer: 1 },
  { id: 67, category: "Acts & Early Church", question: "After his conversion, Saul became known by what name as he led missionary journeys?", options: ["Peter", "Paul", "Silas", "Barnabas"], answer: 1 },
  { id: 68, category: "Acts & Early Church", question: "The Jerusalem Council in Acts 15 addressed the major question of:", options: ["Where to build the temple", "Whether Gentile believers needed to follow Jewish law, especially circumcision", "Who should be the next apostle", "How to divide church funds"], answer: 1 },
  { id: 69, category: "Acts & Early Church", question: "Peter's vision of a sheet with unclean animals in Acts 10 led directly to:", options: ["The stoning of Stephen", "The gospel opening to Gentiles, starting with Cornelius", "Paul's shipwreck", "The Jerusalem famine relief"], answer: 1 },
  { id: 70, category: "Acts & Early Church", question: "Paul's missionary journeys in Acts primarily established churches throughout:", options: ["Egypt and North Africa", "Asia Minor, Greece, and eventually Rome", "Britain", "Mesopotamia only"], answer: 1 },
  { id: 71, category: "Acts & Early Church", question: "The book of Acts ends with Paul:", options: ["Executed in Jerusalem", "Under house arrest in Rome, still preaching", "Returning to Tarsus", "Founding the church in Corinth"], answer: 1 },
  { id: 72, category: "Acts & Early Church", question: "Barnabas is notable in Acts for:", options: ["Writing the book of Acts", "Encouraging and vouching for Paul, and partnering in early missionary work", "Betraying Paul", "Being the first Gentile convert"], answer: 1 },
  { id: 73, category: "Acts & Early Church", question: "In Acts, the early Jerusalem believers were noted for practicing:", options: ["Strict isolation from each other", "Sharing possessions, fellowship, prayer, and the apostles' teaching", "Separate worship for Jews and Gentiles", "Weekly fasting only"], answer: 1 },
  { id: 74, category: "Acts & Early Church", question: "Which city's believers were first called 'Christians,' according to Acts 11?", options: ["Jerusalem", "Antioch", "Rome", "Ephesus"], answer: 1 },

  // ---------------- Epistles (Romans–Jude) ----------------
  { id: 75, category: "Epistles", question: "Paul's letter to the Romans is often seen as his most systematic explanation of:", options: ["Church leadership structure", "The gospel — sin, justification by faith, and salvation", "End-times prophecy", "Spiritual gifts only"], answer: 1 },
  { id: 76, category: "Epistles", question: "Complete the verse: 'For all have sinned and fall short of the ___.' (Romans 3:23)", options: ["law", "glory of God", "commandments", "covenant"], answer: 1 },
  { id: 77, category: "Epistles", question: "1 Corinthians famously addresses divisions in the church, including a chapter often read at weddings about:", options: ["Faith", "Hope", "Love", "Grace"], answer: 2 },
  { id: 78, category: "Epistles", question: "Galatians is Paul's strongest defense of the idea that believers are justified by faith rather than by:", options: ["Baptism", "Works of the law", "Church membership", "Prophecy"], answer: 1 },
  { id: 79, category: "Epistles", question: "Ephesians describes the church using the image of:", options: ["A vineyard", "The body of Christ, united under one head", "A flock without a shepherd", "A field of wheat"], answer: 1 },
  { id: 80, category: "Epistles", question: "Complete the verse: 'I can do all things through him who ___ me.' (Philippians 4:13)", options: ["saves", "strengthens", "loves", "chose"], answer: 1 },
  { id: 81, category: "Epistles", question: "Colossians emphasizes the supremacy of Christ, describing him as:", options: ["A created angel", "'The image of the invisible God,' in whom all things hold together", "Merely a wise teacher", "Subordinate to the law"], answer: 1 },
  { id: 82, category: "Epistles", question: "1 & 2 Thessalonians deal significantly with questions about:", options: ["Church governance", "The return of Christ and hope for believers who have died", "Jewish dietary law", "Roman taxation"], answer: 1 },
  { id: 83, category: "Epistles", question: "The 'Pastoral Epistles' (1 & 2 Timothy, Titus) are primarily concerned with:", options: ["End-times timelines", "Instructions for church leadership and sound doctrine", "Missionary travel logs", "Old Testament law"], answer: 1 },
  { id: 84, category: "Epistles", question: "Hebrews argues extensively that Jesus is superior to the old covenant system by presenting him as:", options: ["A new Moses only", "The great high priest whose sacrifice fulfills and surpasses the old system", "A replacement for the prophets only", "An angel greater than others"], answer: 1 },
  { id: 85, category: "Epistles", question: "James is known for its practical emphasis that genuine faith is shown by:", options: ["Correct doctrine alone", "Works/action, not just belief", "Church attendance", "Spiritual gifts"], answer: 1 },
  { id: 86, category: "Epistles", question: "1 Peter was written to encourage believers who were facing:", options: ["Wealth and comfort", "Suffering and persecution", "Doctrinal disputes only", "Famine"], answer: 1 },
  { id: 87, category: "Epistles", question: "1 John repeatedly emphasizes two core themes: that God is light, and that God is:", options: ["Wrath", "Love", "Judgment", "Silence"], answer: 1 },

  // ---------------- Revelation & Famous Verses ----------------
  { id: 88, category: "Revelation & Famous Verses", question: "The book of Revelation was written by John, likely while exiled on the island of:", options: ["Cyprus", "Patmos", "Crete", "Malta"], answer: 1 },
  { id: 89, category: "Revelation & Famous Verses", question: "Revelation opens with letters addressed to:", options: ["The apostles", "Seven churches in Asia Minor", "The Jewish diaspora", "Rome's emperor"], answer: 1 },
  { id: 90, category: "Revelation & Famous Verses", question: "Revelation's central hope, described in its closing chapters, is:", options: ["The destruction of Rome only", "A new heaven and new earth where God dwells with his people", "The restoration of temple sacrifices", "A restored Davidic kingdom on earth alone"], answer: 1 },
  { id: 91, category: "Revelation & Famous Verses", question: "Complete the verse: 'Trust in the LORD with all your heart... in all your ways acknowledge him, and he will ___.' (Proverbs 3:5-6)", options: ["bless your house", "make straight your paths", "protect your children", "grant you peace"], answer: 1 },
  { id: 92, category: "Revelation & Famous Verses", question: "Complete the verse: 'Be strong and courageous. Do not be frightened, and do not be dismayed, for the LORD your God is with you wherever you ___.' (Joshua 1:9)", options: ["go", "stand", "rest", "walk"], answer: 0 },
  { id: 93, category: "Revelation & Famous Verses", question: "Which verse is most associated with the wages of sin and the free gift of God?", options: ["'The wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord.'", "'For all have sinned and fall short of the glory of God.'", "'There is no condemnation for those in Christ Jesus.'", "'Nothing can separate us from the love of God.'"], answer: 0 },
  { id: 94, category: "Revelation & Famous Verses", question: "'And we know that for those who love God all things work together for good, for those who are called according to his purpose' is found in:", options: ["Philippians", "Romans", "Ephesians", "1 Corinthians"], answer: 1 },
  { id: 95, category: "Revelation & Famous Verses", question: "Complete the verse: 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to ___.' (Philippians 4:6)", options: ["one another", "God", "the church", "the elders"], answer: 1 },
  { id: 96, category: "Revelation & Famous Verses", question: "Which verse is most commonly cited as the 'Great Commandment'?", options: ["'Love the LORD your God with all your heart... and love your neighbor as yourself.'", "'Go and make disciples of all nations.'", "'Do to others as you would have them do to you.'", "'Blessed are the peacemakers.'"], answer: 0 },
  { id: 97, category: "Revelation & Famous Verses", question: "Complete the verse: 'This is the day that the LORD has made; let us ___ and be glad in it.' (Psalm 118:24)", options: ["sing", "rejoice", "dance", "worship"], answer: 1 },
  { id: 98, category: "Revelation & Famous Verses", question: "Complete the verse: 'Put on the whole armor of God, that you may be able to stand against the schemes of the ___.' (Ephesians 6:11)", options: ["enemy", "devil", "world", "flesh"], answer: 1 },
  { id: 99, category: "Revelation & Famous Verses", question: "Complete the verse: 'Come to me, all who labor and are heavy laden, and I will give you ___.' (Matthew 11:28)", options: ["peace", "rest", "strength", "hope"], answer: 1 },
  { id: 100, category: "Revelation & Famous Verses", question: "The shortest verse in the Bible, John 11:35, simply reads:", options: ["'Jesus prayed.'", "'Jesus wept.'", "'Jesus wept for Lazarus.'", "'Jesus was moved.'"], answer: 1 },

];
